### DISCUSSION TITLE
What is the correct way to do DPO training on CHAT preference datasets?

### DISCUSSION THREAD

**Discussion by abhinand5** [axolotl-ai-cloud/axolotl#1399] [Q&A]
**Dataset Used:** [argilla/dpo-mix-7k](https://huggingface.co/datasets/argilla/dpo-mix-7k)

**!! The fields are dict instead of strings. !!**

![image](https://github.com/OpenAccess-AI-Collective/axolotl/assets/35622449/cd13c7c2-60ca-4106-ac0b-949c6d94d5f7)

So I have written a script to tokenize them and then save the tokenized prompts in a dataset, which I am trying to then load and do the training with custom dataset type.

```yaml
rl: dpo
datasets:
  - path: dpo-mix-formatted.jsonl
    ds_type: json
    split: train
    type:
        field_prompt: prompt
        field_chosen: chosen
        field_rejected: rejected
```

The training is running currently, but I am not sure if this is the correct way to do this. Can anyone confirm?
