### DISCUSSION TITLE
ShareGPT tool datasets handling

### DISCUSSION THREAD

**Discussion by hasan9090** [axolotl-ai-cloud/axolotl#1768] [Q&A] [answered]
I would like to similarly treat any other tool handling dataset like for example this version of glaive lilacai/glaive-function-calling-v2-sharegpt , which already is in sharegpt, or similarly any other custom dataset of that format. 
I found this MR related to this topic https://github.com/axolotl-ai-cloud/axolotl/pull/1365 .
When trying to do so and orientating at the mentioned configs, I cannot make it work to recognize the tool role as 3rd role in axolotl and don't really know if it is possible and how the config has to look like?
From the above , I think setting type also to sharegpt.load_glaive would not work as the dataset is already in sharegpt and this function seems to convert it first to that format? But I do think I need to set the conversation to "chatml_glaive" since this is handling the tool role? When using the following config it is not working for me:

datasets:
-path: lilacai/glaive-function-calling-v2-sharegpt
type: sharegpt
conversation: chatml_glaive
field_human: human
field_model: gpt

It would be nice if someone could help.
Thanks Hasan

**Comment by NanoCode012** [comment, marked as answer]
Terribly sorry we missed this post. I just found this while going through discussions. I'm leaving this answer below for any future readers.

A few months ago, we have added improved support for other roles and chat_template support.

For current axolotl, the way to load this dataset
```yaml
datasets:
    - path: lilacai/glaive-function-calling-v2-sharegpt
      type: chat_template
      chat_template: chatml
      message_field_role: from
      message_field_content: value
      field_messages: conversations
```

Note; This dataset adds `<|endoftext|>` in its text, so you may want to use it for EOS (which would conflict with normal chatml). An alternative would be to use your own custom `chat_template_jinja: ` to parse it into your preferred output format and handle capitalizing USER/ASSISTANT as shown in their readme.
