### DISCUSSION TITLE
Sample packing masks the <end_of_turn> token

### DISCUSSION THREAD

**Discussion by ganler** [axolotl-ai-cloud/axolotl#2259] [Q&A] [answered]
* I've SFT'ing models using Gemma template with sample packing enabled and `train_on_input` set to false.
* The SFT'ed model cannot stop generation.
* By checking the tokenization, I found the `<end_of_turn>` token is masked with -100
* Not sure if this would cause `<end_of_turn>` untrained

<img width="572" alt="image" src="https://github.com/user-attachments/assets/bc3b6cbd-6194-459e-9479-2620d5637562" />

I wonder if this is expected and if so how to make sure `<end_of_turn>` is also trained so that the conversation can end gracefully.

**Comment by NanoCode012** [comment]
Hello! Yes, that could be one possible reason behind your issue.

Could I see how your dataset config yaml looks like and perhaps a sample demo row (could be fake data) of your dataset?

**Comment by ganler** [comment]
```yaml
# model specific
base_model: mistralai/Mistral-7B-v0.3 # it was some internal models but mistral should also repro the bug
chat_template: gemma

# hot hyperparameters
output_dir: ./outputs/mistral-gemma-it
sequence_len: 4096
sample_packing: true
gradient_accumulation_steps: 1
micro_batch_size: 2
learning_rate: 1e-5

# dataset -- can be anything that uses OpenAI chat format / role: ..., content: ...
datasets: 
  - path: [PLACE HOLDER]
    type: chat_template
    field_messages: messages
trust_remote_code: true

# utility
resume_from_checkpoint:
logging_steps: 10
warmup_steps: 100
max_grad_norm: 1.0
save_strategy: "no" # only save the final checkpoint

# trivial
flash_attention: true
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
bf16: true
tf32: false
pad_to_sequence_len: true # mem stability
train_on_inputs: false
seed: 666

num_epochs: 1
optimizer: adamw_torch_fused
lr_scheduler: cosine
```
