### DISCUSSION TITLE
How do I use only a portion of a dataset?

### DISCUSSION THREAD

**Discussion by mashdragon** [axolotl-ai-cloud/axolotl#2280] [Q&A] [answered]
I noticed that I cannot set a fractional `num_epochs` value. How do I instruct axolotl to use only a small portion of my dataset?

**Comment by NanoCode012** [comment]
> I noticed that I cannot set a fractional num_epochs value.

I just looked at Trainer docs, and it seems that `num_epochs` can actually be a float. Currently in Axolotl, we expect it to be an integer. Is it useful for it to be a float?

> How do I instruct axolotl to use only a small portion of my dataset?

https://github.com/axolotl-ai-cloud/axolotl/blob/8fb72cbc0b94129141bae5fa4d84edd23b648af6/docs/config.qmd#L90

You can use this config in your dataset section. For example, the below would split the data and use only 10% (10 piece = 100%).

```yaml
datasets:
  - path: fozziethebeat/alpaca_messages_2k_test
    type: chat_template
    shards: 10
```

**Reply by mashdragon** [reply]
Yes, it would definitely be useful to allow floats. There are times when I would like to train for, say, 1.2 epochs instead of just 1 without having to modify the dataset.

Thank you for the tip about shards. That is working. I did come across a discrepancy between when ```ValueError: eval dataset split is too small for sample_packing. You should set `eval_sample_packing: False`.``` appeared in the preprocess stage vs training (succeeded in preprocess, error appeared in training with 20 shards in my config and only succeeded in training when I took shards down to 10).

Sadly I was getting OOM with `eval_sample_packing: false` in the configuration when training when trying to use anywhere from 20 to 11 shards. My total dataset size is 100k, so I'm confused why it would be too small at 5k samples or even up to 9k (after dropping long sequences), it still produced this exception.

Also, would you mind explaining the split option (as shown in https://github.com/axolotl-ai-cloud/axolotl/blob/main/examples/llama-3/fft-8b-liger-fsdp.yaml)? It doesn't affect the dataset load size when I change it, even though I assumed it would via the docs at https://huggingface.co/docs/datasets/v3.2.0/loading#slice-splits

**Reply by NanoCode012** [reply]
> it would definitely be useful to allow floats. There are times when I would like to train for, say, 1.2 epochs instead of just 1 without having to modify the dataset.

I think you can create a new feature request to make `epochs: float`, it would be a good-first-issue. 

However, why would you need to modify the dataset?

>  I did come across a discrepancy between when ValueError: eval dataset split is too small for sample_packing. You should set `eval_sample_packing: False`. appeared in the preprocess stage vs training (succeeded in preprocess, error appeared in training with 20 shards in my config and only succeeded in training when I took shards down to 10).

That's weird it passes the preprocess but not train. I think they used the same `prepare_dataset` function which does this check.

> Sadly I was getting OOM with eval_sample_packing: false in the configuration when training when trying to use anywhere from 20 to 11 shards. My total dataset size is 100k, so I'm confused why it would be too small at 5k samples or even up to 9k (after dropping long sequences), it still produced this exception.

Do you mean out of system memory or out of vram?

> Also, would you mind explaining the split option (as shown in https://github.com/axolotl-ai-cloud/axolotl/blob/main/examples/llama-3/fft-8b-liger-fsdp.yaml)? It doesn't affect the dataset load size when I change it, even though I assumed it would via the docs at https://huggingface.co/docs/datasets/v3.2.0/loading#slice-splits

Hm, it should affect split. We should be passing it to `load_dataset`. https://github.com/axolotl-ai-cloud/axolotl/blob/8fb72cbc0b94129141bae5fa4d84edd23b648af6/src/axolotl/utils/data/shared.py#L150-L162

You could try printing `dataset.num_rows` after this line to be sure.

**Reply by mashdragon** [reply]
> I think you can create a new feature request to make `epochs: float`, it would be a good-first-issue.

Thanks, I'll make a PR for the change once I have time.

> Do you mean out of system memory or out of vram?

It was out of VRAM for this problem (sample packing). But actually the reason for this discussion was I ran out of system RAM during model saving on this config and after training for a whole epoch of my data it didn't save. I wanted to try again with a tiny sample to see if my new configuration with a larger swap space would OOM on system memory or not.

> You could try printing `dataset.num_rows` after this line to be sure.

Thanks for the pointer. I was loading data from a local file, which for that Axolotl currently doesn't pass anything to the split parameter. I could also make a PR for this, too, once I verify that the split parameter works for that.

**Reply by NanoCode012** [reply]
> I was loading data from a local file, which for that Axolotl currently doesn't pass anything to the split parameter. I could also make a PR for this, too, once I verify that the split parameter works for that.

Oh, that makes sense. I don't think we had support passing the split param since it's just a local file. I wasn't aware it was possible. If it works, this would help improve parity.

> I wanted to try again with a tiny sample to see if my new configuration with a larger swap space would OOM on system memory or not.

You could do `save_steps: 5` to check if you can successfully save early. How much RAM/VRAM do you have and for which model? Adding swap should help.

**Reply by mashdragon** [reply]
This is a FFT of Llama-3.2-3B, since I hit GPU OOM trying the fft-8b-liger-fdsp config on Llama 3.1 8B. RAM/VRAM is 96GB RAM/2x24GB VRAM.

With 30GB swap added, it saved successfully on my mini-run.

> You could do save_steps: 5 to check if you can successfully save early.

Oh, I wasn't aware, that's great. Due to the sample packing issue, I had to wait an hour for the mini-run to complete, so maybe next time this will help avoid that.

(And by the way, thank you so much for the help! You have already saved me many hours of struggling or trying to locate things within the code on my own!)

**Reply by NanoCode012** [reply]
Hm, that's weird. 96GB RAM should be enough for 3B model, though I haven't really benchmarked how much RAM liger+fsdp offload uses. 

> With 30GB swap added, it saved successfully on my mini-run.

That's good to hear. How's the current vram/ram % usage?

> (And by the way, thank you so much for the help! You have already saved me many hours of struggling or trying to locate things within the code on my own!)

Happy to help!

**Reply by mashdragon** [reply]
Yes, I think having users share VRAM/RAM usage is really helpful since I get frequently disappointed by OOM errors on my hardware. It would be nice if the docs listed some benchmarks. Under this configuration:

<details><summary>config.yml</summary>

```yaml
base_model: ./Llama-3.2-3B

plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_glu_activation: true
liger_fused_linear_cross_entropy: true

strict: false

chat_template: llama3
datasets:
  - path: my-dataset.jsonl
    type: completion
    split: train[60%:70%]
    text_column: text

dataset_prepared_path: last_run_prepared
val_set_size: 0.02
output_dir: ./3b-fft

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 3
num_epochs: 1
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 2e-5

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

# From warning, When using FSDP full shard, instead of using `gradient_checkpointing` in TrainingArguments, please use `activation_checkpointing` in `fsdp_config`. The former introduces a redundant AllGather operation in backward pass. Reference: https://github.com/huggingface/transformers/issues/30404
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 100
evals_per_epoch: 2
eval_table_size:
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_limit_all_gathers: true
  fsdp_sync_module_states: true
  fsdp_offload_params: true
  fsdp_use_orig_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_backward_prefetch: BACKWARD_PRE
  activation_checkpointing: true
special_tokens:
  pad_token: <|finetune_right_pad_id|>
  eos_token: <|eot_id|>
  ```
  </details>
  
See the micro batch size of 3. A size of 4 would OOM for me. Also, see in my comment that I got a warning to set `activation_checkpointing` in `fsdp_config` rather than `gradient_checkpointing`. Maybe we should change Axolotl's FSDP examples.

The current VRAM usage during training is 22300 MB/24576 MB for each of the 2 GPUs. System RAM is harder for me to interpret, but free says Used 33G/Free 2.5G/Shared 33G/Buff-cache 62.5G/Available 30G, and top shows this for the two Python workers:

```
  VIRT    RES    SHR
 69.5g  30.2g  16.9g
 69.0g  30.2g  16.9g
```

So I think the 33G shared comes from the two workers. So something like 66GB total (including base system)?

I wonder if I could reduce the context size, hopefully not by too much, and possibly still fit in the Llama 3.1 8B finetune with a micro batch size of 1 (for 4096 context it went OOM from what I remember). That would probably be a lot more desired than the 3B model.
