### DISCUSSION TITLE
Save LoRA weight in bfloat16

### DISCUSSION THREAD

**Discussion by thehs29** [axolotl-ai-cloud/axolotl#2400] [Q&A]
My base model (llama3.2-3b-instruct) is in bfloat16, however, the lora adapter after training is float32, thus causing difference when merging adapter into a base model weight. So I would like to ask is there any way to have the LoRA adapter weights in bfloat16?

I train the model using FSDP + LoRA

**Comment by NanoCode012** [comment]
Hey, do you have your config available to share? Did you set `bf16: true`? What kind of system did you train on?

**Reply by thehs29** [reply]
Thanks for response, my training config:

accelerate.yaml
```yaml
compute_environment: LOCAL_MACHINE
debug: true
distributed_type: FSDP
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

train.yaml
```yaml
# model
base_model: meta-llama/Llama-3.2-3B-Instruct
trust_remote_code: true
force_download: false
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

# loading
load_in_8bit: false
load_in_4bit: false
strict: false
bf16: true
fp16:
tf32: true
bfloat16: true

wandb_project: hsthe-llm
wandb_name: train-10-03-25
wandb_log_model: checkpoint

# overrides_of_model_kwargs:
#   use_cache: false

# datasets
datasets:
  - path: /home/hsthe/data/training
    type: chat_template
    chat_template: tokenizer_default
    ds_type: arrow
    field_messages: messages
    roles_to_train: ["assistant"]
    train_on_split: train

val_set_size: 0
shuffle_merged_datasets: true

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

# lora
adapter: lora
lora_model_dir:
lora_r: 64
lora_alpha: 128
lora_dropout: 0.05
lora_target_linear: true
lora_target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - gate_proj
  - down_proj
  - up_proj
lora_fan_in_fan_out:

lora_modules_to_save:
  # - embed_tokens
  # - lm_head

output_dir: /home/hsthe/output/training_output

save_safetensors: true

gradient_accumulation_steps: 2
micro_batch_size: 2
num_epochs: 2
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 0.00002

train_on_inputs: false
group_by_length: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:

local_rank:
logging_steps: 10
xformers_attention:
flash_attention: true

optim_target_modules:
  - self_attn  # for llama

resume_from_checkpoint:

warmup_ratio: 0.05
evals_per_epoch: 0
saves_per_epoch: 10
save_total_limit: 4
debug:
deepspeed:
weight_decay: 0.0
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_limit_all_gathers: true
  fsdp_sync_module_states: true
  fsdp_offload_params: true
  fsdp_use_orig_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sharding_strategy: FULL_SHARD
special_tokens:
  pad_token: "<|eot_id|>"
```
