### DISCUSSION TITLE
Custom Prompt Format Error

### DISCUSSION THREAD

**Discussion by MatanVetzler** [axolotl-ai-cloud/axolotl#761] [Q&A]
I have a jsonl file of the following format: {"system": "...", "human": "...", "bot: "..."}.
I need the prompt format to be:
```
<system>: {system}
<human>: {human}
<bot>: {bot}
```

When trying to configure the yaml as such I'm getting "Tokenizer result is empty. You may want to audit your dataset. Empty text requested for tokenization.":

```
datasets:
  - path: resources/training_data.jsonl
    ds_type: json
    type:
      system_prompt: ""
      system_format: ""
      field_system:
      field_instruction: system
      field_input: human
      field_output: bot
      format: "<system>: {system}\n<human>: {human}\n<bot>: {bot}"
```

please advise
