### DISCUSSION TITLE
Add special token to llama 2

### DISCUSSION THREAD

**Discussion by generalsvr** [axolotl-ai-cloud/axolotl#764] [Q&A] [answered]
Hello! How can I add a new token to the model? I need a special separator token to interrupt streaming response. Can I just simply add a new token to _special_tokens_ config? Like this:

```
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
  my_token: "<end>"
```
