### ISSUE TITLE
pydantic warning Field "model_type" has conflict with protected namespace "model_".

### ISSUE THREAD

**Issue by ehartford** [axolotl-ai-cloud/axolotl#1335]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

no pydantic warnings

### Current behaviour

/home/ubuntu/miniconda3/envs/axolotl/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_type" has conflict with protected namespace "model_".

### Steps to reproduce

train model

### Config yaml

```yaml
base_model: google/gemma-7b
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: /home/ubuntu/datasets/dolphin-coder-unsloth/dolphin201-sharegpt2.jsonl
    type: sharegpt
  - path: /home/ubuntu/datasets/dolphin-coder-unsloth/dolphin-coder-translate-sharegpt2.jsonl
    type: sharegpt
  - path: /home/ubuntu/datasets/dolphin-coder-unsloth/dolphin-coder-codegen-sharegpt2.jsonl
    type: sharegpt
  - path: /home/ubuntu/datasets/dolphin-coder-unsloth/data-evol_instruct-sharegpt2.jsonl
    type: sharegpt
  - path: /home/ubuntu/datasets/dolphin-coder-unsloth/data-oss_instruct-decontaminated-sharegpt2.jsonl
    type: sharegpt
  - path: /home/ubuntu/datasets/not_samantha_norefusals.jsonl
    type: sharegpt
  - path: /home/ubuntu/datasets/openhermes2_5-sharegpt.jsonl
    type: sharegpt

val_set_size: 0
output_dir: /home/ubuntu/dolphin-2.8-gemma-7b

adapter: qlora
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

wandb_project: dolphin
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 8
micro_batch_size: 2
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 2e-4

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 2
debug:
deepspeed: deepspeed_configs/zero2.json
weight_decay: 0.0
fsdp:
fsdp_config:
```

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
