### ISSUE TITLE
Loading local Dataset saved via `save_to_disk` fails

### ISSUE THREAD

**Issue by fozziethebeat** [axolotl-ai-cloud/axolotl#1430]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I create some local dataset that I saved via calling `ds.save_to_disk('some_path')`

If I then configure Axolotl to load a dataset from `save_path` such as

```yaml
datasets: 
- path: tmp_dataset
...
```

I would expect it to load much like loading from a remote huggingface repo.

### Current behaviour

The loaded dataset includes the contents of `state.json` rather than the actual dataset and everything fails.

### Steps to reproduce

1. Save some dataset to disk via `save_to_disk`
2. Configure Axolotl to read from that dataset
3. See Axolotl crash

### Config yaml

```yaml
datasets:
- path: local_dataset_saved_via_save_to_disk
  type:
    field_instruction: prompts
    field_output: responses
    field_system: system
    format: '[INST] {instruction} [/INST]'
    no_input_format: '[INST] {instruction} [/INST]'
    system_prompt: ''
```

### Possible solution

In `src/axolotl/utils/data.py` I see that for local directory paths, datasets are loaded via `load_dataset`.  `load_from_disk` seems to be the new preferred solution (this is also a comment).  I manually hacked this in and everything worked without a problem.

Would switching that to `load_from_disk` break anything? It seems like a reasonable quick fix (which I can do)

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main/4e69aa4

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
