### ISSUE TITLE
Unfreeze layers in mixtral does not work as expected

### ISSUE THREAD

**Issue by funeric555** [axolotl-ai-cloud/axolotl#1464]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

The config for mixtral.yml contains examples for unfreeze such as: "^model.embed_tokens.weight$[:32000]" and "^lm_head.weights$"

The expected behavior is that the layers listed in the config mixtral.yml are unfrozen, in this case embed_tokens would be unfrozen for 0-31999 and lm_head would be unfrozen.

### Current behaviour

The layers are not unfrozen as expected.

"All parameters are frozen. Model will not be trained."

### Steps to reproduce

Uncomment the lines in the mixtral.yml config:

unfrozen_parameters:
  \- ^lm_head.weight$
  \- ^model.embed_tokens.weight$[:32000]

Then run as shown in the readme:
accelerate launch -m axolotl.cli.train examples/mistral/mixtral.yml --deepspeed deepspeed_configs/zero2.json

### Config yaml

```yaml
base_model: mistralai/Mixtral-8x7B-v0.1
model_type: AutoModelForCausalLM
tokenizer_type: LlamaTokenizer
trust_remote_code: true

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: tatsu-lab/alpaca
    type: alpaca
dataset_prepared_path: last_run_prepared
val_set_size: 0.0
output_dir: ./qlora-out

## You can optionally freeze the entire model and unfreeze a subset of parameters
unfrozen_parameters:
  - ^lm_head.weight$
  - ^model.embed_tokens.weight$[:32000]
#  - model.layers.2[0-9]+.block_sparse_moe.gate
#  - model.layers.2[0-9]+.block_sparse_moe.experts
#  - model.layers.3[0-9]+.block_sparse_moe.gate
#  - model.layers.3[0-9]+.block_sparse_moe.experts

model_config:
  output_router_logits: true

adapter: qlora
lora_model_dir:

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
#lora_target_modules:
#  - gate
#  - q_proj
#  - k_proj
#  - v_proj
#  - o_proj
#  - w1
#  - w2
#  - w3

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 2
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

loss_watchdog_threshold: 5.0
loss_watchdog_patience: 3

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed: deepspeed_configs/zero2.json
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
```

### Possible solution

Two part fix:
1: change "match" to search at: https://github.com/OpenAccess-AI-Collective/axolotl/blob/main/src/axolotl/utils/freeze.py#L195
2: Match the substring in the layers instead of anchored match:
change the yml regex to: `- embed_tokens.[^\s]*weight$[:32000]`  or `- lm_head.[^\s]*weight`

Some details:
When running the config as shown, the layer names are different than shown:
For example:
`base_model.model.model.layers.0.self_attn.q_proj.lora_A.default.weight`
`base_model.model.model.embed_tokens.modules_to_save.default.weight`

Also - in a usecase where the goal is to freeze the existing embeddings, and unfreeze only newly added ones, you should use [32000:] to indicate that the newly added token embeddings are unfrozen, not the existing ones. If the goal is to unfreeze the embedding layer, then no need to add the slice at the end.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10.12

### axolotl branch-commit

main/dbrx

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
