### ISSUE TITLE
Prediction (Table) Artifacts for MLFlow Logger Not Reporting Any Results

### ISSUE THREAD

**Issue by DavidFarago** [axolotl-ai-cloud/axolotl#1524]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

A Prediction (Table) Artifacts with ... appearing in "Evaluation" in MLFlow, see https://github.com/OpenAccess-AI-Collective/axolotl/issues/1505 and https://github.com/OpenAccess-AI-Collective/axolotl/issues/490.

### Current behaviour

No Prediction (Table) Artifacts appearing in "Evaluation" in MLFlow:
![image (1)](https://github.com/OpenAccess-AI-Collective/axolotl/assets/1004626/9349240c-5257-491e-acde-1c04ad90a71c)

### Steps to reproduce

1) Add the following to your `axolotl.yaml`:
```
wandb_mode: disabled

mlflow_tracking_uri: http://127.0.0.1:5000/
mlflow_experiment_name: mistral_lora_intent_plus_qualification
hf_mlflow_log_artifacts:  true
```
2) Enable MLFlow on runpod:
```
pip install mlflow
mkdir -p /workspace/mlflow
echo "Starting mlflow server"
tmux kill-window -t mlflow || true
tmux new-window \
    -n mlflow \
    -c /workspace/mlflow \
    "mlflow ui --host 127.0.0.1 --port 5000; bash"

echo "Enable port forwarding with:"
echo "ssh -L 5000:127.0.0.1:5000 -p $RUNPOD_TCP_PORT_22 root@$RUNPOD_PUBLIC_IP -N"
```
3) Start finetuning:
```
cd /workspace/axolotl
accelerate launch -m axolotl.cli.train /workspace/${MODEL_REPO}/axolotl.yml
```

### Config yaml

```yaml
base_model: # private model
base_model_config: # private model

model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  # several private datasets
dataset_prepared_path: last_run_prepared-sharegpt
val_set_size: 0.05
output_dir: ./qlora-out-sharegpt

adapter: qlora
lora_model_dir:

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

wandb_mode: disabled

mlflow_tracking_uri: http://127.0.0.1:5000
mlflow_experiment_name: mistral_lora_intent_plus_qualification
hf_mlflow_log_artifacts:  true

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 2
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 10
save_steps:
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
```

### Possible solution

I am now looking into adding some test cases to help debug and avoid regressions.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main/132eb74

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
