### ISSUE TITLE
Merging issue LLama3-70b. ValueError: We need an 'offload-dir' to dispatch this model:

### ISSUE THREAD

**Issue by BenjaminGantenbein** [axolotl-ai-cloud/axolotl#1569]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Adapter should be merged without any errors. 

### Current behaviour

When merging with CUDA_VISIBLE_DEVICES="" I get this error. With llama2-70b I had no issues with my system ram (196gb). Lllama3 merging throws this error: 

[2024-04-26 15:18:54,972] [DEBUG] [axolotl.load_lora:966] [PID:6416] [RANK:0] Loading pretrained PEFT - LoRA
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/brutus/Desktop/Bachelorarbeit/bsc-thesis/axolotl/src/axolotl/cli/merge_lora.py", line 48, in <module>
    fire.Fire(do_cli)
  File "/home/brutus/anaconda3/envs/p311-cu121-axolotl/lib/python3.11/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brutus/anaconda3/envs/p311-cu121-axolotl/lib/python3.11/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/brutus/anaconda3/envs/p311-cu121-axolotl/lib/python3.11/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brutus/Desktop/Bachelorarbeit/bsc-thesis/axolotl/src/axolotl/cli/merge_lora.py", line 44, in do_cli
    do_merge_lora(cfg=parsed_cfg, cli_args=parsed_cli_args)
  File "/home/brutus/Desktop/Bachelorarbeit/bsc-thesis/axolotl/src/axolotl/cli/__init__.py", line 141, in do_merge_lora
    model, tokenizer = load_model_and_tokenizer(cfg=cfg, cli_args=cli_args)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brutus/Desktop/Bachelorarbeit/bsc-thesis/axolotl/src/axolotl/common/cli.py", line 53, in load_model_and_tokenizer
    model, _ = load_model(cfg, tokenizer, inference=cli_args.inference)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brutus/Desktop/Bachelorarbeit/bsc-thesis/axolotl/src/axolotl/utils/models.py", line 795, in load_model
    model, lora_config = load_adapter(model, cfg, cfg.adapter)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brutus/Desktop/Bachelorarbeit/bsc-thesis/axolotl/src/axolotl/utils/models.py", line 839, in load_adapter
    return load_lora(model, cfg, inference=inference)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brutus/Desktop/Bachelorarbeit/bsc-thesis/axolotl/src/axolotl/utils/models.py", line 971, in load_lora
    model = PeftModel.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brutus/anaconda3/envs/p311-cu121-axolotl/lib/python3.11/site-packages/peft/peft_model.py", line 356, in from_pretrained
    model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
  File "/home/brutus/anaconda3/envs/p311-cu121-axolotl/lib/python3.11/site-packages/peft/peft_model.py", line 760, in load_adapter
    dispatch_model(
  File "/home/brutus/anaconda3/envs/p311-cu121-axolotl/lib/python3.11/site-packages/accelerate/big_modeling.py", line 374, in dispatch_model
    raise ValueError(
ValueError: We need an `offload_dir` to dispatch this model according to this `device_map`, the following submodules need to be offloaded: base_model.model.model.layers.28, base_model.model.model.layers.29, base_model.model.model.layers.30, base_model.model.model.layers.31, base_model.model.model.layers.32, base_model.model.model.layers.33, base_model.model.model.layers.34, base_model.model.model.layers.35, base_model.model.model.layers.36, base_model.model.model.layers.37, base_model.model.model.layers.38, base_model.model.model.layers.39, base_model.model.model.layers.40, base_model.model.model.layers.41, base_model.model.model.layers.42, base_model.model.model.layers.43, base_model.model.model.layers.44, base_model.model.model.layers.45, base_model.model.model.layers.46, base_model.model.model.layers.47, base_model.model.model.layers.48, base_model.model.model.layers.49, base_model.model.model.layers.50, base_model.model.model.layers.51, base_model.model.model.layers.52, base_model.model.model.layers.53, base_model.model.model.layers.54, base_model.model.model.layers.55, base_model.model.model.layers.56, base_model.model.model.layers.57, base_model.model.model.layers.58, base_model.model.model.layers.59, base_model.model.model.layers.60, base_model.model.model.layers.61, base_model.model.model.layers.62, base_model.model.model.layers.63, base_model.model.model.layers.64, base_model.model.model.layers.65, base_model.model.model.layers.66, base_model.model.model.layers.67, base_model.model.model.layers.68, base_model.model.model.layers.69, base_model.model.model.layers.70, base_model.model.model.layers.71, base_model.model.model.layers.72, base_model.model.model.layers.73, base_model.model.model.layers.74, base_model.model.model.layers.75, base_model.model.model.layers.76, base_model.model.model.layers.77, base_model.model.model.layers.78, base_model.model.model.layers.79, base_model.model.model.norm, base_model.model.lm_head.

### Steps to reproduce

1. Fine tune model.
2. Try to merge on system ram

### Config yaml

```yaml
My yaml file: 
base_model: meta-llama/Meta-Llama-3-70B-Instruct
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false


datasets:
  - path: bsc-thesis/datasets/polishes_english_2k.jsonl
    ds_type: json
    type: sharegpt
    split: train
val_set_size: 0.05
output_dir: ./out

adapter: qlora

sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true
eval_sample_packing: false

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:



wandb_project: 
wandb_entity:
wandb_watch:
wandb_name: 
wandb_log_model: 

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 3
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: true
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
evals_per_epoch: 3
eval_table_size:
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
special_tokens:
  pad_token: "<|end_of_text|>"
```

### Possible solution

Maybe some device mapping isse?

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

update llama-3 config (#1543)

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
