### ISSUE TITLE
Streaming large datasets not working with pretrain_multipack_attn: true

### ISSUE THREAD

**Issue by timpal0l** [axolotl-ai-cloud/axolotl#1597]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

It should be possible to do pretraining on a large dataset using streaming and the `pretrain_multipack_attn` set to `true`.

### Current behaviour

```
 1 wandb: WARNING Saving files without folders. If you want to preserve sub directories pass base_path to wandb.save, i.e. wandb.save("/mnt/folder/file.h5", base_path="/mnt")
 2   0%|          | 0/172203 [00:00<?, ?it/s]Traceback (most recent call last):
 3   File "<frozen runpy>", line 198, in _run_module_as_main
 4   File "<frozen runpy>", line 88, in _run_code
 5   File "/home/tim.ai/axolotl/src/axolotl/cli/train.py", line 59, in <module>
 6     fire.Fire(do_cli)
 7   File "/home/tim.ai/anaconda3/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
 8     component_trace = _Fire(component, args, parsed_flag_args, context, name)
 9                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
10   File "/home/tim.ai/anaconda3/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
11     component, remaining_args = _CallAndUpdateTrace(
12                                 ^^^^^^^^^^^^^^^^^^^^
13   File "/home/tim.ai/anaconda3/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
14     component = fn(*varargs, **kwargs)
15                 ^^^^^^^^^^^^^^^^^^^^^^
16   File "/home/tim.ai/axolotl/src/axolotl/cli/train.py", line 35, in do_cli
17     return do_train(parsed_cfg, parsed_cli_args)
18            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
19   File "/home/tim.ai/axolotl/src/axolotl/cli/train.py", line 55, in do_train
20     return train(cfg=cfg, cli_args=cli_args, dataset_meta=dataset_meta)
21            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22   File "/home/tim.ai/axolotl/src/axolotl/train.py", line 170, in train
23     trainer.train(resume_from_checkpoint=resume_from_checkpoint)
24   File "/home/tim.ai/anaconda3/lib/python3.11/site-packages/transformers/trainer.py", line 1837, in train
25     return inner_training_loop(
26            ^^^^^^^^^^^^^^^^^^^^
27   File "/home/tim.ai/anaconda3/lib/python3.11/site-packages/transformers/trainer.py", line 2143, in _inner_training_loop
28     for step, inputs in enumerate(epoch_iterator):
29   File "/home/tim.ai/anaconda3/lib/python3.11/site-packages/accelerate/data_loader.py", line 655, in __iter__
30     next_batch, next_batch_info = self._fetch_batches(main_iterator)
31                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
32   File "/home/tim.ai/anaconda3/lib/python3.11/site-packages/accelerate/data_loader.py", line 609, in _fetch_batches
33     batches.append(next(iterator))
34                    ^^^^^^^^^^^^^^
35   File "/home/tim.ai/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
36     data = self._next_data()
37            ^^^^^^^^^^^^^^^^^
38   File "/home/tim.ai/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
39     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
40            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
41   File "/home/tim.ai/anaconda3/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
42     data.append(next(self.dataset_iter))
43                 ^^^^^^^^^^^^^^^^^^^^^^^
44   File "/home/tim.ai/anaconda3/lib/python3.11/site-packages/datasets/iterable_dataset.py", line 1379, in __iter__
45     for key, example in ex_iterable:
46   File "/home/tim.ai/anaconda3/lib/python3.11/site-packages/datasets/iterable_dataset.py", line 678, in __iter__
47     yield from self._iter()
48   File "/home/tim.ai/anaconda3/lib/python3.11/site-packages/datasets/iterable_dataset.py", line 717, in _iter
49     transformed_batch.update(self.function(*function_args, **self.fn_kwargs))
50                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
51   File "/home/tim.ai/axolotl/src/axolotl/utils/data/pretraining.py", line 23, in encode_pretraining
52     res = tokenizer(
53           ^^^^^^^^^^
54   File "/home/tim.ai/anaconda3/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2858, in __call__
55     encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
56                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
57   File "/home/tim.ai/anaconda3/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2916, in _call_one
58     raise ValueError(
59 ValueError: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
```

### Steps to reproduce

```accelerate launch -m axolotl.cli.train my_yaml.yaml```

### Config yaml

```yaml
base_model: meta-llama/Meta-Llama-3-8B
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

pretraining_dataset:
  - path: /home/tim.ai/.cache/huggingface/datasets/timpal0l___pile
    type: completion

pretrain_multipack_attn: false
dataset_processes: 32
val_set_size: 0.0
output_dir: /share/tim.ai/pile/small
pretrain_multipack_buffer_size: 100000
#max_steps: 1000
max_steps: 186554

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true
eval_sample_packing: false

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 2e-5

train_on_inputs: false
group_by_length: false
bf16: true
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
auto_resume_from_checkpoints:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 100
evals_per_epoch:
eval_table_size:
save_steps: 375
saves_per_epoch:
debug:
deepspeed: /home/tim.ai/axolotl/deepspeed_configs/zero2.json
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: <|end_of_text|>
```

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
@timpal0l lmk if #1603 fixes this for you.

**Comment by Ahmedn1** [comment]
I am having the same issue except my dataset is not large (144 records). I want to finetune a model and my yaml is like this: 

```yaml
base_model: meta-llama/Meta-Llama-3-8B
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

max_steps: 100
pretraining_dataset:
   - path: dummy_dataset
     type: completion # (I also tried `pretrain`)
dataset_prepared_path:
val_set_size: 0.3
output_dir: ./outputs/finetuned_model

adapter: qlora
lora_model_dir:

sequence_len: 8192
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: false

lora_r: 16
lora_alpha: 16
lora_dropout: 0
lora_target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 8
num_epochs: 2
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16: true
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 4
xformers_attention:
flash_attention: true

warmup_steps: 2
evals_per_epoch: 1
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
```

And my dataset is in JSONL format following this format: 

```jsonl
{"text": ""}
{"text": ""}
...
```

And I keep getting: 

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank0]:   File "<frozen runpy>", line 88, in _run_code
[rank0]:   File "/home/axolotl/src/axolotl/cli/train.py", line 70, in <module>
[rank0]:     fire.Fire(do_cli)
[rank0]:   File "/home/bsci/venv/lib/python3.11/site-packages/fire/core.py", line 143, in Fire
[rank0]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/bsci/venv/lib/python3.11/site-packages/fire/core.py", line 477, in _Fire
[rank0]:     component, remaining_args = _CallAndUpdateTrace(
[rank0]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/bsci/venv/lib/python3.11/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
[rank0]:     component = fn(*varargs, **kwargs)
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/axolotl/src/axolotl/cli/train.py", line 38, in do_cli
[rank0]:     return do_train(parsed_cfg, parsed_cli_args)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/axolotl/src/axolotl/cli/train.py", line 66, in do_train
[rank0]:     return train(cfg=cfg, cli_args=cli_args, dataset_meta=dataset_meta)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/axolotl/src/axolotl/train.py", line 170, in train
[rank0]:     trainer.train(resume_from_checkpoint=resume_from_checkpoint)
[rank0]:   File "/home/bsci/venv/lib/python3.11/site-packages/transformers/trainer.py", line 1539, in train
[rank0]:     return inner_training_loop(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/bsci/venv/lib/python3.11/site-packages/transformers/trainer.py", line 1836, in _inner_training_loop
[rank0]:     for step, inputs in enumerate(epoch_iterator):
[rank0]:   File "/home/bsci/venv/lib/python3.11/site-packages/accelerate/data_loader.py", line 677, in __iter__
[rank0]:     next_batch, next_batch_info = self._fetch_batches(main_iterator)
[rank0]:                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/bsci/venv/lib/python3.11/site-packages/accelerate/data_loader.py", line 631, in _fetch_batches
[rank0]:     batches.append(next(iterator))
[rank0]:                    ^^^^^^^^^^^^^^
[rank0]:   File "/home/bsci/venv/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
[rank0]:     data = self._next_data()
[rank0]:            ^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/bsci/venv/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
[rank0]:     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/bsci/venv/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
[rank0]:     data.append(next(self.dataset_iter))
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/bsci/venv/lib/python3.11/site-packages/datasets/iterable_dataset.py", line 1389, in __iter__
[rank0]:     for key, example in ex_iterable:
[rank0]:   File "/home/bsci/venv/lib/python3.11/site-packages/datasets/iterable_dataset.py", line 679, in __iter__
[rank0]:     yield from self._iter()
[rank0]:   File "/home/bsci/venv/lib/python3.11/site-packages/datasets/iterable_dataset.py", line 718, in _iter
[rank0]:     transformed_batch.update(self.function(*function_args, **self.fn_kwargs))
[rank0]:                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/axolotl/src/axolotl/utils/data/pretraining.py", line 23, in encode_pretraining
[rank0]:     res = tokenizer(
[rank0]:           ^^^^^^^^^^
[rank0]:   File "/home/bsci/venv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2803, in __call__
[rank0]:     encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/bsci/venv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2862, in _call_one
[rank0]:     raise ValueError(
[rank0]: ValueError: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
```
