### ISSUE TITLE
Llama3-8b: LlamaForCausalLM.forward() got an unexpected keyword argument 'length'

### ISSUE THREAD

**Issue by DMR92** [axolotl-ai-cloud/axolotl#1700]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I expect the training run to finish and save the weights for the finetuned model

### Current behaviour

Hi,

after starting the training process for a Llama-3 8b LoRa finetuning on Jarvis using Axolotl I get the following error: `TypeError: LlamaForCausalLM.forward() got an unexpected keyword argument 'length'.`

### Steps to reproduce

I picked 1 x RTX6000Ada on Jarvis Labs with the Axolotl template. After starting a jupyter notebook I slightly modified the default config for lora-8b. In particular, I only added `hub_model_id`, `wandb_entity`, `wandb_project` and `eval_sample_packing: false` to the default example config, but left the rest unchanged. 

### Config yaml

```yaml
hub_model_id: d4niel92/llama3-8B_alpaca_2k_lora

wandb_entity: d4nielmeyer
wandb_project: llama3-8b_alpaca_2k_lora

base_model: meta-llama/Meta-Llama-3-8B
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: true
load_in_4bit: false
strict: false

datasets:
  - path: mhenrichsen/alpaca_2k_test
    type: alpaca

dataset_prepared_path:
val_set_size: 0.05
output_dir: ./outputs/lora-out

sequence_len: 4096
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true

adapter: lora
lora_model_dir:
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_modules_to_save:
  - embed_tokens
  - lm_head

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 4
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
s2_attention:

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
   pad_token: <|end_of_text|>
```

### Possible solution

Similar key errors related to this forward method were solved by setting flash_attention to false, but that didn't solve it in my case. 

I also ran a training with exactly the same dataset as input for **tiny-llama**, and everything worked out perfectly. Checking the input data if a sample contains a string "length" returned no result. 

Any ideas what might cause the issue and how I can solve it?

Thank you 🙏 

### Which Operating Systems are you using?

- [ ] Linux
- [X] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main/851ccb1

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
