### ISSUE TITLE
Extremely High Loss, which quickly goes to *0* by the End; Configs that Were Fine Are Broken Now

### ISSUE THREAD

**Issue by e-p-armstrong** [axolotl-ai-cloud/axolotl#1806]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

The same configs should produce a model similar to what it had done before the update around July 30. There should be no dramatic instability with the loss values.

### Current behaviour

Whereas before the loss started around 2.3 and proceeded to be something around 0.8 by the end of a 5-epoch training run, now, with the same config, it starts at 4.2 (!) and goes to 0 in places by the end. Accordingly, the resulting model is overfit to hell and braindead.

In this WandB graph, the blue thing was the loss graph of a model before this problem was introduced. The ones that spike in the middle are all ones after the fact, with slightly different settings as I tried to figure out what was going on.

![image](https://github.com/user-attachments/assets/ecb34749-bff6-4096-8781-ce792e26acd6)

![image](https://github.com/user-attachments/assets/52e5f067-4a54-40b2-9a41-28de81bf1d39)

### Steps to reproduce

Train a LoRA with the given config and some data. Observe obscenely high loss values and overfitting where there was none before.

### Config yaml

```yaml
base_model: abacusai/Llama-3-Smaug-8B
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: json
    data_files: ./training_data_2/final_annotation_convs.jsonl
    type: chat_template
    field_messages: conversations
    message_field_role: from
    message_field_content: value
    roles:
      user:
        - human
      assistant:
        - gpt
      system:
        - system
  - path: json
    data_files: ./training_data_2/rephrase.jsonl
    type: chat_template
    field_messages: conversations
    message_field_role: from
    message_field_content: value
    roles:
      user:
        - human
      assistant:
        - gpt
      system:
        - system
  
dataset_prepared_path: ./training_datafolder
output_dir: ./training_out

adapter: lora

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true
shuffle_merged_datasets: true

lora_r: 128
lora_alpha: 256
lora_dropout: 0.20
lora_target_linear: true
lora_fan_in_fan_out:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

wandb_project: fixed-cleaned-dropout-and-neftune
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
eval_batch_size: 1
num_epochs: 5
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 0.0002
weight_decay: 0
# Gradient clipping max norm
max_grad_norm: 1.0
noisy_embedding_alpha: 5

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: unsloth
early_stopping_patience:
resume_from_checkpoint: 
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

# fsdp:
  # - full_shard
  # - auto_wrap
# fsdp_config:
  # fsdp_offload_params: false
  # fsdp_state_dict_type: FULL_STATE_DICT
  # fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
# warmup_steps: 10
warmup_steps: 0
auto_resume_from_checkpoints: false
#warmup_ratio: 0.5
eval_steps: 10
saves_per_epoch: 1
eval_sample_packing: false
save_total_limit: 2
debug:
deepspeed: deepspeed_configs/zero2.json
special_tokens:
  pad_token: "<|end_of_text|>"
```

### Possible solution

Potentially useful for finding a reason: rolling back axolotl versions and doing a new pip install -r requirements does NOT seem to fix it, at least with the version I am rolling back to. So maybe this is an issue with an underlying dependency? I have no idea how to address it though, or how to find which dep is the problem.

IDK if axolotl is the problem here, but as it stands, I can't train anything anymore. Would appreciate support in knowing what settings to turn off to fix this, until those deps fix their darn problems. Very concerned about this bug becoming a permenant thing in case it only happens during edge cases.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11.9

### axolotl branch-commit

main/78b42a3fe13c49e317bc116b9999c30e070322cc

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
