### ISSUE TITLE
inst chat jinja template does not match prompt format used while training with `conversation: mistral`

### ISSUE THREAD

**Issue by nyxkrage** [axolotl-ai-cloud/axolotl#1832]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Given the following conversations
```py
messages_with_sys = [
  { "role": "system", "content": "SYSTEM MESSAGE" },
  { "role": "user", "content": "USER MESSAGE" },
  { "role": "assistant", "content": "ASSISTANT MESSAGE" },
  { "role": "user", "content": "USER MESSAGE" },
  { "role": "assistant", "content": "ASSISTANT MESSAGE" },
]
messages_no_sys = [
  { "role": "user", "content": "USER MESSAGE" },
  { "role": "assistant", "content": "ASSISTANT MESSAGE" },
  { "role": "user", "content": "USER MESSAGE" },
  { "role": "assistant", "content": "ASSISTANT MESSAGE" },
]
```

Decoding the tokens provided by the debug output from preprocessing it results in:  
with_sys: `<s>[INST]  SYSTEM MESSAGE\nUSER MESSAGE[/INST] ASSISTANT MESSAGE</s>[INST] USER MESSAGE[/INST] ASSISTANT MESSAGE</s>`  
no_sys: `<s>[INST] USER MESSAGE[/INST] ASSISTANT MESSAGE</s>[INST] USER MESSAGE[/INST] ASSISTANT MESSAGE</s>`  

I would expect the chat template inserted in the tokenizer config to match what is used during training.

### Current behaviour

When calling `.apply_chat_template` with a `tokenizer_config.json` containing the chat_template from `src/axolotl/utils/chat_templates.py` results in
```python
In [3]: AutoTokenizer.from_pretrained("template_axolotl").apply_chat_template(messages_with_sys, tokenize=False)
TemplateError: Conversation roles must alternate user/assistant/user/assistant/... 
In [4]: AutoTokenizer.from_pretrained("template_axolotl").apply_chat_template(messages_no_sys, tokenize=False)
Out[4]: '<s>[INST] USER MESSAGE [/INST]ASSISTANT MESSAGE</s>[INST] USER MESSAGE [/INST]ASSISTANT MESSAGE</s>'
```

### Steps to reproduce

1. Save 2 datasets with the following rows duplicated a couple times to allow debugging the tokenization
test_convo_no_sys.jsonl:
```json
{ "conversations": [{ "from": "user", "value": "USER MESSAGE" }, { "from": "assistant", "value": "ASSISTANT MESSAGE" }, { "from": "user", "value": "USER MESSAGE" }, { "from": "assistant", "value": "ASSISTANT MESSAGE" }] }
```
test_convo_with_sys.jsonl:
```json
{ "conversations": [{ "from": "system", "value": "SYSTEM MESSAGE" }, { "from": "user", "value": "USER MESSAGE" }, { "from": "assistant", "value": "ASSISTANT MESSAGE" }, { "from": "user", "value": "USER MESSAGE" }, { "from": "assistant", "value": "ASSISTANT MESSAGE" }] }
```
2. run `python -m axolotl.cli.preprocess config.yml --debug`
3. parse just the tokens from the debug output
```bash
echo '[' && echo '<s>(-100, 1) [INST](-100, 3) US(-100, 2991) ER(-100, 1493) ME(-100, 14603) SS(-100, 2151) AGE(-100, 6898) [/INST](-100, 4) ASS(9370, 9370) IST(8816, 8816) ANT(13506, 13506) ME(14603, 14603) SS(2151, 2151) AGE(6898, 6898) </s>(2, 2) [INST](-100, 3) US(-100, 2991) ER(-100, 1493) ME(-100, 14603) SS(-100, 2151) AGE(-100, 6898) [/INST](-100, 4) ASS(9370, 9370) IST(8816, 8816) ANT(13506, 13506) ME(14603, 14603) SS(2151, 2151) AGE(6898, 6898) </s>(2, 2)' | sed -e 's/)/,\n/g' | sed -e 's/.*, //' && echo ']'
```
this gives an output like so (put on a single line for brevity's sake)
```py
[ 1, 3, 2991, 1493, 14603, 2151, 6898, 4, 9370, 8816, 13506, 14603, 2151, 6898, 2, 3, 2991, 1493, 14603, 2151, 6898, 4, 9370, 8816, 13506, 14603, 2151, 6898, 2, ]
```
4. decode this with the tokenizer of the trained model
```py
AutoTokenizer.from_pretrained("mistralai/Mistral-7B-Instruct-v0.3").decode([1, 3, 2991, 1493, 14603, 2151, 6898, 4, 9370, 8816, 13506, 14603, 2151, 6898, 2, 3, 2991, 1493, 14603, 2151, 6898, 4, 9370, 8816, 13506, 14603, 2151, 689, 8, 2, ]))
```
5. check output against apply_chat_template
```py
tokenizer = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-Instruct-v0.3")
tokenizer.chat_template = "{% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif %}{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}"
tokenizer.apply_chat_template(messages_no_sys, tokenize=False)
tokenizer.apply_chat_template(messages_with_sys, tokenize=False)
```

### Config yaml

```yaml
base_model: mistralai/Mistral-7B-Instruct-v0.3 
model_type: MistralForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: ./test_convo_(no/with)_sys.jsonl
    type: sharegpt
    conversation: mistral
chat_template: inst

dataset_prepared_path: last_run_prepared
output_dir: ./outputs/mistral-test

adapter: 
lora_model_dir:

sequence_len: 512
sample_packing: true
pad_to_sequence_len: true

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1

loss_watchdog_threshold: 5.0
loss_watchdog_patience: 3

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
```

### Possible solution

I have written a Jinja template that does seem to match the format that axolotl used when training
```
{%- if messages[0]['role'] == 'system' %}\n    {%- set system_message = messages[0]['content'] %}\n    {%- set loop_messages = messages[1:] %}\n{%- else %}\n    {%- set loop_messages = messages %}\n{%- endif %}\n\n{{- bos_token }}\n{%- for message in loop_messages %}\n    {%- if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}\n        {{- raise_exception('After the optional system message, conversation roles must alternate user/assistant/user/assistant/...') }}\n    {%- endif %}\n    {%- if message['role'] == 'user' %}\n        {%- if loop.first and system_message is defined %}\n            {{- '[INST]  ' + system_message + '\\n' + message['content'] + '[/INST]' }}\n        {%- else %}\n            {{- '[INST] ' + message['content'] + '[/INST]' }}\n        {%- endif %}\n    {%- elif message['role'] == 'assistant' %}\n        {{- ' ' + message['content'] + eos_token}}\n    {%- else %}\n        {{- raise_exception('Only user and assistant roles are supported, with the exception of an initial optional system message!') }}\n    {%- endif %}\n{%- endfor %}\n
```

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main/b1d29212222f5dd566fab5453e3fd342089c8191

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
