### ISSUE TITLE
Failed to Inference on same workstation that finished the fine-tuning

### ISSUE THREAD

**Issue by ruiding-uchicago** [axolotl-ai-cloud/axolotl#1971]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

successfully inference on the same machine
I successfully finetuned based on official example yaml file:
accelerate launch -m axolotl.cli.train examples/llama-3/qlora-fsdp-70b.yaml

but on the same machine, cannot inference based on the tutorial:
accelerate launch -m axolotl.cli.inference examples/llama-3/qlora-fsdp-70b.yaml --lora_model_dir="./outputs/out/qlora-llama3-70b"

previously, for smaller ones:
accelerate launch -m axolotl.cli.train examples/openllama-3b/lora.yml
then inference:
accelerate launch -m axolotl.cli.inference examples/openllama-3b/lora.yml --lora_model_dir="./outputs/lora-out"
succeeded.

### Current behaviour

2024-10-14 11:50:59,023] [INFO] [axolotl.load_model:970] [PID:510809] [RANK:3] GPU memory usage after adapters: 0.000GB ()
[rank1]: Traceback (most recent call last):
[rank1]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank1]:   File "<frozen runpy>", line 88, in _run_code
[rank1]:   File "/home/ruiding/Downloads/axolotl/src/axolotl/cli/inference.py", line 38, in <module>
[rank1]:     fire.Fire(do_cli)
[rank1]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 135, in Fire
[rank1]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank1]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 468, in _Fire
[rank1]:     component, remaining_args = _CallAndUpdateTrace(
[rank1]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
[rank1]:     component = fn(*varargs, **kwargs)
[rank1]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/ruiding/Downloads/axolotl/src/axolotl/cli/inference.py", line 33, in do_cli
[rank1]:     do_inference(cfg=parsed_cfg, cli_args=parsed_cli_args)
[rank1]:   File "/home/ruiding/Downloads/axolotl/src/axolotl/cli/__init__.py", line 184, in do_inference
[rank1]:     model.to_empty(device=cfg.device)
[rank1]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1036, in to_empty
[rank1]:     return self._apply(lambda t: torch.empty_like(t, device=device), recurse=recurse)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
[rank1]:     module._apply(fn)
[rank1]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
[rank1]:     module._apply(fn)
[rank1]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
[rank1]:     module._apply(fn)
[rank1]:   [Previous line repeated 5 more times]
[rank1]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 804, in _apply
[rank1]:     param_applied = fn(param)
[rank1]:                     ^^^^^^^^^
[rank1]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1036, in <lambda>
[rank1]:     return self._apply(lambda t: torch.empty_like(t, device=device), recurse=recurse)
[rank1]:                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/torch/_prims_common/wrappers.py", line 252, in _fn
[rank1]:     result = fn(*args, **kwargs)
[rank1]:              ^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/torch/_refs/__init__.py", line 4875, in empty_like
[rank1]:     return torch.empty_permuted(
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU  has a total capacity of 23.68 GiB of which 111.81 MiB is free. Including non-PyTorch memory, this process has 23.55 GiB memory in use. Of the allocated memory 23.21 GiB is allocated by PyTorch, and 67.49 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:49<00:00,  1.66s/it]
[rank3]: Traceback (most recent call last):
[rank3]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank3]:   File "<frozen runpy>", line 88, in _run_code
[rank3]:   File "/home/ruiding/Downloads/axolotl/src/axolotl/cli/inference.py", line 38, in <module>
[rank3]:     fire.Fire(do_cli)
[rank3]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 135, in Fire
[rank3]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank3]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 468, in _Fire
[rank3]:     component, remaining_args = _CallAndUpdateTrace(
[rank3]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
[rank3]:     component = fn(*varargs, **kwargs)
[rank3]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/ruiding/Downloads/axolotl/src/axolotl/cli/inference.py", line 33, in do_cli
[rank3]:     do_inference(cfg=parsed_cfg, cli_args=parsed_cli_args)
[rank3]:   File "/home/ruiding/Downloads/axolotl/src/axolotl/cli/__init__.py", line 184, in do_inference
[rank3]:     model.to_empty(device=cfg.device)
[rank3]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1036, in to_empty
[rank3]:     return self._apply(lambda t: torch.empty_like(t, device=device), recurse=recurse)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
[rank3]:     module._apply(fn)
[rank3]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
[rank3]:     module._apply(fn)
[rank3]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
[rank3]:     module._apply(fn)
[rank3]:   [Previous line repeated 5 more times]
[rank3]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 804, in _apply
[rank3]:     param_applied = fn(param)
[rank3]:                     ^^^^^^^^^
[rank3]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1036, in <lambda>
[rank3]:     return self._apply(lambda t: torch.empty_like(t, device=device), recurse=recurse)
[rank3]:                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/torch/_prims_common/wrappers.py", line 252, in _fn
[rank3]:     result = fn(*args, **kwargs)
[rank3]:              ^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/torch/_refs/__init__.py", line 4875, in empty_like
[rank3]:     return torch.empty_permuted(
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^
[rank3]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU  has a total capacity of 23.68 GiB of which 111.81 MiB is free. Including non-PyTorch memory, this process has 23.55 GiB memory in use. Of the allocated memory 23.21 GiB is allocated by PyTorch, and 67.49 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
...
final part of the output:
[2024-10-14 11:50:59,978] [INFO] [axolotl.load_model:970] [PID:510808] [RANK:2] GPU memory usage after adapters: 0.000GB ()
W1014 11:51:00.674000 137451942680384 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 510806 closing signal SIGTERM
W1014 11:51:00.675000 137451942680384 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 510808 closing signal SIGTERM
W1014 11:51:00.675000 137451942680384 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 510809 closing signal SIGTERM
E1014 11:51:04.653000 137451942680384 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 1 (pid: 510807) of binary: /home/ruiding/anaconda3/envs/axolotl/bin/python
Traceback (most recent call last):
  File "/home/ruiding/anaconda3/envs/axolotl/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1165, in launch_command
    multi_gpu_launcher(args)
  File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/commands/launch.py", line 799, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ruiding/anaconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
axolotl.cli.inference FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-14_11:51:00
  host      : SYS-740GP-TNRT
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 510807)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

### Steps to reproduce

1. after successfully fintuning, I checked there are indeed checkpoint files all ready under ./outputs/out/qlora-llama3-70b
2. but running the same yaml for inference: accelerate launch -m axolotl.cli.inference examples/openllama-3b/lora.yml --lora_model_dir="./outputs/lora-out" would end up with not enough memory error

### Config yaml

```yaml
base_model: casperhansen/llama-3-70b-fp16
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer  # PreTrainedTokenizerFast

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: tatsu-lab/alpaca
    type: alpaca
dataset_prepared_path: last_run_prepared
val_set_size: 0.05
output_dir: ./outputs/out/qlora-llama3-70b

adapter: qlora
lora_model_dir:

sequence_len: 512
sample_packing: false
pad_to_sequence_len: true

lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 2
micro_batch_size: 1
num_epochs: 2
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 0.00001

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
ddp_timeout: 99999
ddp_bucket_cap_mb: 128
ddp_broadcast_buffers: False
pad_to_sequence_len: true
warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_limit_all_gathers: true
  fsdp_sync_module_states: true
  fsdp_offload_params: true
  fsdp_use_orig_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sharding_strategy: FULL_SHARD
special_tokens:
  pad_token: <|end_of_text|>
```

### Possible solution

Please tell me if it is the hardware problem, 
I have a 4 of A5500 workstation, and as I menteiond, successfully ran the official example as yaml pasted here, throught that 4 of 24GB = 96 GB GPU memory
but the issue is that is it not possible to use the same machine for inference? qlora-fsdp has reduced the requirment of machine for fine-tuning, but not able to directly inference? or is that I need to modify the launch command?

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main/4d6490b

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
