### ISSUE TITLE
Falcon + FSDP

### ISSUE THREAD

**Issue by winglian** [axolotl-ai-cloud/axolotl#203]
per https://discord.com/channels/1104757954588196865/1111279858136383509/1116644094484164609

SyLM — 06/09/2023 4:24 AM
Yeah, I did that 
I wondered if there was a reason I was not aware of, and this was a hard "no", no need then for me to continue trying!
[4:30 AM]
Latest tests, with regard to that and the oom/memory leak at save:

With current axolotl main, older axolotl docker, updated accelerate only, I'm able
to run with fsdp (config via accelerate and  use_orig_params: true, needs a tweak in the code as well)
same fsdp config via axolotl crashes (or I did not config it the real same way? no 1:1 match between the 2 ways to config)
no more extra memory use when saving, allowing me to save more frequently and use way larger micro batches

So, 
fsdp definitely is possible with Falcon, but needs more info about its precise config, and see why it crashes when config'd in yml
oom/leak are related to some lib version, very likely peft. I'll compare and try to debug between my 2 setups, one oom the other one not.
[4:31 AM]
--
For reference, my working accelerate config, Falcon

```
more /root/.cache/huggingface/accelerate/default_config.yaml
compute_environment: LOCAL_MACHINE
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  fsdp_offload_params: true
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_transformer_layer_cls_to_wrap: DecoderLayer
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

```
fsdp:
fsdp_config:
  use_orig_params: true
```
I had to unindent these 2 lines
https://github.com/OpenAccess-AI-Collective/axolotl/blob/320beb20f407e5ffec00f79bf8e3e378be4feda9/src/axolotl/utils/trainer.py#L99

I tried to use fsdp: True  instead and this crashes.

**Comment by NanoCode012** [comment]
FSDP seems to work with Falcon (running one test now). No PEFT.

```yaml
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_offload_params: true
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_transformer_layer_cls_to_wrap: DecoderLayer
```

We should consider remove the below block:

https://github.com/OpenAccess-AI-Collective/axolotl/blob/a94f2eecb1ada9a344b0436786a18077a489b1cc/src/axolotl/utils/validation.py#L61-L62

Edit: Nvm, getting mismatch error like Utensil I think. 

```
work = group._allgather_base(output_tensor, input_tensor)
RuntimeError: output tensor size must be equal to world_size times input tensor size
```
