### ISSUE TITLE
Training OOMs when it shouldn't due to bizarrely large cache

### ISSUE THREAD

**Issue by mfirth-truffle** [axolotl-ai-cloud/axolotl#2143]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I'm using llama 3B across 8 80GB GPUs with DS Zero3. It shouldn't OOM

### Current behaviour

OOMs even at just 2048 sequence length or 4096 sequence length. While the actual parameters on each GPU are small, the cache somehow balloons to 70GB+ and I OOM every time

### Steps to reproduce

Use the attached config yaml and train...

### Config yaml

```yaml
base_model: meta-llama/Llama-3.2-3B-Instruct

datasets:
  - path: axolotl_format_data_llama_wm.json
    type: input_output
dataset_prepared_path: last_run_prepared
    
output_dir: ./models/llama_wm
sequence_length: 2048

wandb_project: agent-v0
wandb_name: llama-3b_wm

train_on_inputs: false
gradient_accumulation_steps: 4
micro_batch_size: 1
num_epochs: 3
optimizer: adamw_torch
learning_rate: 2e-5

logging_steps: 5

warmup_steps: 10
saves_per_epoch: 1
weight_decay: 0.0

deepspeed: axolotl/deepspeed_configs/zero3_bf16_cpuoffload_all.json

special_tokens:
  pad_token: <|end_of_text|>
```

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
