### ISSUE TITLE
Mistral Nemo 12B Completion Training Fails from `unexpected keyword argument 'token_type_ids'`

### ISSUE THREAD

**Issue by xzuyn** [axolotl-ai-cloud/axolotl#2225]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Expected behaviour is it trains without erroring out.

### Current behaviour

You get an error; `TypeError: MistralForCausalLM.forward() got an unexpected keyword argument 'token_type_ids'` or `TypeError: lce_forward() got an unexpected keyword argument 'token_type_ids'` (when using liger).

[Toasty Pigeon noticed it here](https://discord.com/channels/1104757954588196865/1111279858136383509/1264382777504038964).

[Seungduk Kim noticed it here](https://discord.com/channels/1104757954588196865/1111279858136383509/1266483042705211557).

[Caitlyn G. noticed it here](https://discord.com/channels/1104757954588196865/1111279858136383509/1298464339992514581) and [here](https://discord.com/channels/1104757954588196865/1111279858136383509/1308928833939832883).

Training with instruction data apparently works fine though, just completion is broken. I don't know if this only happens with Mistral Nemo 12B or if it happens with other Mistral models as well.

### Steps to reproduce

1. Setup latest axolotl.
2. Start training with the config provided.

### Config yaml

```yaml
# Model checkpointing config
output_dir: ./nemo-fail-test-qlora
save_steps: 10
save_safetensors: true
save_total_limit: 2
save_only_model: true

# Model architecture config
base_model: mistralai/Mistral-Nemo-Base-2407
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

# Mixed precision training config
bf16: true
fp16: false
tf32: false

# Model loading config
load_in_8bit: false
load_in_4bit: true
strict: false

# Sequence config
sequence_len: 2048
min_sample_len: 64
sample_packing: true
eval_sample_packing: true
pad_to_sequence_len: true
train_on_inputs: false
group_by_length: false

# LoRA adapter config
adapter: qlora
lora_model_dir:
lora_r: 16
lora_alpha: 1
lora_dropout: 0.125
peft_layers_to_transform:
peft_use_dora:
peft_use_rslora: true
peft_layer_replication:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj
lora_modules_to_save:

# Dataset config
datasets:
# Completion
  # Non-Story Data
  - path: PJMixers-Dev/ToastyPigeon_SpringDragon-axo
    type: completion
val_set_size: 0
eval_strategy:
eval_steps:
dataset_prepared_path: ./nemo-fail-test-ds
shuffle_merged_datasets: true

# Training hyperparameters
num_epochs: 1
gradient_accumulation_steps: 1
micro_batch_size: 1
eval_batch_size: 1
warmup_steps: 10
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 1e-5
cosine_min_lr_ratio: 0.1
loraplus_lr_ratio: 8
loraplus_lr_embedding: 1e-6  # 10x lower than main LR
weight_decay: 0.1
max_grad_norm: 1
logging_steps: 1

# Model optimization
gradient_checkpointing: unsloth
sdp_attention: true
## Liger
plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_layer_norm: true
liger_glu_activation: true
liger_fused_linear_cross_entropy: true

# DeepSpeed
deepspeed:

# Garbage Collection
gc_steps: 1

# Debug config
debug: true
seed: 42

# Token config
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  pad_token: "<pad>"
tokens:
```

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.12.3

### axolotl branch-commit

main/7a38dbe

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
