### ISSUE TITLE
Gradient Accumulation Causes Loss And Grad Norm To Multiply By GA Steps Used (BS1GA8 Is ~8x Larger Than BS8GA1)

### ISSUE THREAD

**Issue by xzuyn** [axolotl-ai-cloud/axolotl#2262]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I assume the loss and grad_norm should be relatively similar. I know they won't be identical, but I don't think this behaviour is intended.

### Current behaviour

With the provided *very tiny* test config using `micro_batch_size=1` with `gradient_accumulation_steps=8` results in 8x higher loss than `micro_batch_size=8` with `gradient_accumulation_steps=1`.

That means with BS8GA1 it's starting at `~10.5 loss` and ending `~6.8 loss`.
But with BS1GA8 it's starting at `~83.7 loss` and ending at `~50 loss`.

The loss follows roughly the same curve, but the grad_norm seems a bit different, and the eval loss is lower on BS1GA8.

![Screenshot from 2025-01-15 18-24-09](https://github.com/user-attachments/assets/2606e943-1e42-4263-9bb9-62721457fd4b)

---

Possibly related; I've been having some issues ever since the very first transformers/TRL GA fix and I don't think it was every fully solved (at least for me?). [Such as when I was trying to do KTO with TRL itself (not within axolotl) and the change caused the loss to go from 0.5 all the way up to 32.](https://discord.com/channels/1104757954588196865/1111279858136383509/1300552478936530975)

### Steps to reproduce

1. Setup latest axolotl.
2. Start training with the config provided.
3. Start training again with the same cached dataset, but with GA and BS amounts swapped.

### Config yaml

```yaml
# Weights and Biases logging config
wandb_project: one-layer-tiny-mistral-55.4M
wandb_name: one-layer-mistral-tiny-55.4M-FFT-bs8ga1

# Model checkpointing config
output_dir: ./Outputs/one-layer-mistral-tiny-55.4M-FFT-bs8ga1
save_steps: 50
save_safetensors: true
save_total_limit: 2
save_only_model: true

# Model architecture config
base_model: mergekit-community/one-layer-tiny-mistral
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

# Mixed precision training config
bf16: true
fp16: false
tf32: false

# Model loading config
load_in_8bit: false
load_in_4bit: false
strict: false

# Sequence config
sequence_len: 8192
min_sample_len: 128
sample_packing: true
eval_sample_packing: true
pad_to_sequence_len: true
train_on_inputs: false
group_by_length: false

# Dataset config
datasets:
  - path: PJMixers-Dev/goodwiki-2024-12-04-axo
    type: completion
val_set_size: 512
eval_strategy: steps
eval_steps: 50
dataset_prepared_path: ./00-Tokenized-Datasets/onelayertestset
shuffle_merged_datasets: true

# Training hyperparameters
num_epochs: 1
gradient_accumulation_steps: 1
micro_batch_size: 8
eval_batch_size: 1
warmup_steps: 100
optimizer: adamw_8bit
lr_scheduler: cosine
learning_rate: 1e-5
cosine_min_lr_ratio: 0.1
weight_decay: 0.1
max_grad_norm: 1
logging_steps: 1

# Model optimization
gradient_checkpointing: unsloth
sdp_attention: true
## Liger
plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_layer_norm: true
liger_glu_activation: true
liger_fused_linear_cross_entropy: true

# Garbage Collection
gc_steps: 1

# Debug config
debug: true
seed: 42

# Token config
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  pad_token: "</s>"
tokens:
```

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.12.3

### axolotl branch-commit

main/8606093

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
