### ISSUE TITLE
Can't use Llama3 default chat template with ORPO

### ISSUE THREAD

**Issue by dannnnthemannnn** [axolotl-ai-cloud/axolotl#2325]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

This works: 
```
chat_template: tokenizer_default
rl: orpo
datasets:
  - path: <my-dataset>
    split: train
    type: llama3.default
    field_prompt: prompt
    field_chosen: chosen
    field_rejected: rejected
```

### Current behaviour

Error and warning: `[WARNING] [axolotl.load:21] [PID:4] [RANK:0] unable to load strategy llama3`

### Steps to reproduce

Include a dataset of preferences that are not in chat template format, just raw strings of propmt, chosen, rejected. 

It works on DPO but not on ORPO. (Please let me know if there is anything I should be doing differently)

### Config yaml

```yaml
chat_template: tokenizer_default
rl: orpo
datasets:
  - path: <my-dataset>
    split: train
    type: llama3.default
    field_prompt: prompt
    field_chosen: chosen
    field_rejected: rejected
```

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

main-20250210-py3.11-cu124-2.5.1

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hey, @dannnnthemannnn , could you please try the below?

```yaml
chat_template: tokenizer_default
rl: orpo
datasets:
  - path: <my-dataset>
    split: train
    type: chat_template.default # change this
```
