### ISSUE TITLE
Cloud running with Modal is broken due to mount issue

### ISSUE THREAD

**Issue by reissbaker** [axolotl-ai-cloud/axolotl#2346]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

The following cloud config should work:

```yaml
provider: modal
gpu: l40s
gpu_count: 1
timeout: 86400
volumes:
- mount: /workspace/cache
  name: axolotl-cache
env:
- WANDB_API_KEY
- HF_TOKEN
```

### Current behaviour

Running `axolotl train --config config.yaml --cloud ./cloud_config.yaml` crashes once booted inside Modal, saying that the `config.yaml` doesn't exist in the Docker container. This is because — starting from line 262 in `src/axolotl/cli/cloud/modal_.py` — the config paths are all hardcoded to `/workspace/artifacts/axolotl`, but on line 48 of `src/axolotl/cli/__init__.py`, all local directory data is mounted to `/workspace/mounts` instead.

Mounting to `/workspace/mounts` makes sense to me personally: I assume hardcoding `/workspace/artifacts/axolotl` is an accidental artifact left in from testing this behavior on axolotl itself. Nonetheless, it's broken and AFAICT there is no valid configuration that could make it work, since the mounting code copies the files to one place (which is hardcoded), and the training code expects the files to be in a different place (also hardcoded).

### Steps to reproduce

Take any working axolotl config, and the `cloud_config.yaml` above — or any `cloud_config.yaml` — and try to run it. It won't work because the hardcoded paths are out of sync.

### Config yaml

```yaml
literally any config.yaml
```

### Possible solution

Instead of hardcoding the lookup paths to `/workspace/artifacts/axolotl`, hardcode them to `/workspace/mounts`. I cloned the Axolotl repo, did this, and it works.

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

8dfadc2b3c7f85e4208b74eb93c32f440c7e25b4

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hey @reissbaker , thanks for reporting this issue! Would you be open to making this PR fix?

**Comment by reissbaker** [comment]
PR submitted! https://github.com/axolotl-ai-cloud/axolotl/pull/2347

**Comment by NanoCode012** [comment]
Quick question, do you have the below in your modal config?

```
project_name:
volumes:
  - name: axolotl-data
    mount: /workspace/data
  - name: axolotl-artifacts
    mount: /workspace/artifacts
```
