### ISSUE TITLE
Unable to preprocess GRPO dataset

### ISSUE THREAD

**Issue by junethai-mendel** [axolotl-ai-cloud/axolotl#2368]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Able to run `axolotl preprocess config.yml --debug` with the example GRPO config [here](https://axolotl-ai-cloud.github.io/axolotl/docs/rlhf.html#grpo).

### Current behaviour

Got `[RANK:0] unable to load strategy .rewards`. When a debugger breakpoint's set before line 145 in `axolotl.utils.data.rl.py`, the code run to completion without error. 

> [2025-02-28 05:55:16,580] [DEBUG] [axolotl.load_tokenizer:298] [PID:2690] [RANK:0] EOS: 151643 / <|endoftext|>
[2025-02-28 05:55:16,580] [DEBUG] [axolotl.load_tokenizer:299] [PID:2690] [RANK:0] BOS: None / None
[2025-02-28 05:55:16,580] [DEBUG] [axolotl.load_tokenizer:300] [PID:2690] [RANK:0] PAD: 151643 / <|endoftext|>
[2025-02-28 05:55:16,580] [DEBUG] [axolotl.load_tokenizer:301] [PID:2690] [RANK:0] UNK: None / None
[2025-02-28 05:55:16,584] [WARNING] [axolotl.load:32] [PID:2690] [RANK:0] unable to load strategy .rewards
Traceback (most recent call last):
  File "/usr/local/bin/axolotl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/workspace/poc/rlhf/axolotl/src/axolotl/cli/main.py", line 322, in main
    cli()
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/poc/rlhf/axolotl/src/axolotl/cli/utils.py", line 62, in wrapper
    return func(*args, **filtered_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/poc/rlhf/axolotl/src/axolotl/cli/main.py", line 59, in preprocess
    do_cli(config=config, **kwargs)
  File "/workspace/poc/rlhf/axolotl/src/axolotl/cli/preprocess.py", line 97, in do_cli
    do_preprocess(parsed_cfg, parsed_cli_args)
  File "/workspace/poc/rlhf/axolotl/src/axolotl/cli/preprocess.py", line 51, in do_preprocess
    load_preference_datasets(cfg=cfg, cli_args=cli_args)
  File "/workspace/poc/rlhf/axolotl/src/axolotl/common/datasets.py", line 124, in load_preference_datasets
    train_dataset, eval_dataset = load_prepare_preference_datasets(cfg)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/poc/rlhf/axolotl/src/axolotl/utils/data/rl.py", line 198, in load_prepare_preference_datasets
    train_dataset = load_split(cfg.datasets, cfg)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/poc/rlhf/axolotl/src/axolotl/utils/data/rl.py", line 150, in load_split
    split_datasets[i] = map_dataset(
                        ^^^^^^^^^^^^
  File "/workspace/poc/rlhf/axolotl/src/axolotl/utils/data/rl.py", line 62, in map_dataset
    sig = inspect.signature(ds_transform_fn)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/inspect.py", line 3263, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/inspect.py", line 3011, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/inspect.py", line 2456, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: None is not a callable object

### Steps to reproduce

I followed the steps to replicate the example [here](https://axolotl-ai-cloud.github.io/axolotl/docs/rlhf.html#grpo).

### Config yaml

```yaml
base_model: Qwen/Qwen2.5-0.5B

strict: false

chat_template: qwen_25

rl: grpo

trl:
  beta: 0.001
  max_completion_length: 1024
  use_vllm: True
  vllm_device: auto
  vllm_gpu_memory_utilization: 0.15
  num_generations: 8
  reward_funcs: ["rewards.rand_reward_func"]    # format: '{file_name}.{fn_name}'

datasets:
  - path: openai/gsm8k
    name: main
    type: rewards.oai_gsm8k_transform

dataset_prepared_path: last_run_prepared
val_set_size: 0.0
output_dir: ./outputs/qwen-2b-grpo

sequence_len: 2048
sample_packing: false
pad_to_sequence_len: true

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 4
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 0.000005
warmup_ratio: 0.1

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
```

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

main/75cbd15

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.
