### ISSUE TITLE
Bugs in training on google colab

### ISSUE THREAD

**Issue by daksh1053** [axolotl-ai-cloud/axolotl#2373]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Training should happen on colab, when doing the example training 

!axolotl train examples/llama-3/lora-1b.yml

### Current behaviour

During execution of !axolotl train examples/llama-3/lora-1b.yml, training stops with this error

[2025-02-28 20:20:47,154] [INFO] [axolotl.utils.config.models.input.check_bf16:1693] [PID:4476] [RANK:0] bf16 support detected, but not enabled for this configuration.[39m
object address  : 0x787975d3f640
object refcount : 2
object type     : 0x92bc20
object type name: OSError
object repr     : OSError("Can't load the configuration of 'meta-llama/Llama-3.2-3B'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'meta-llama/Llama-3.2-3B' is the correct path to a directory containing a config.json file")
lost sys.stderr

same error occours for any base_model.

The complete output of the run is

The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
2025-02-28 20:20:36.275807: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-28 20:20:36.294620: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1740774036.317551    4476 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1740774036.324453    4476 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-28 20:20:36.347794: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2025-02-28 20:20:40,566] [INFO] [datasets.<module>:54] [PID:4476] PyTorch version 2.5.1+cu124 available.
[2025-02-28 20:20:40,567] [INFO] [datasets.<module>:66] [PID:4476] Polars version 1.14.0 available.
[2025-02-28 20:20:40,567] [INFO] [datasets.<module>:77] [PID:4476] Duckdb version 1.1.3 available.
[2025-02-28 20:20:40,568] [INFO] [datasets.<module>:112] [PID:4476] TensorFlow version 2.18.0 available.
[2025-02-28 20:20:40,569] [INFO] [datasets.<module>:125] [PID:4476] JAX version 0.4.33 available.
[2025-02-28 20:20:43,163] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-02-28 20:20:43,256] [INFO] [root.spawn:60] [PID:4476] x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -c /tmp/tmpef0wd4hx/test.c -o /tmp/tmpef0wd4hx/test.o
[2025-02-28 20:20:43,275] [INFO] [root.spawn:60] [PID:4476] x86_64-linux-gnu-gcc /tmp/tmpef0wd4hx/test.o -laio -o /tmp/tmpef0wd4hx/a.out
[2025-02-28 20:20:43,633] [INFO] [root.spawn:60] [PID:4476] x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -c /tmp/tmprh_4fdjc/test.c -o /tmp/tmprh_4fdjc/test.o
[2025-02-28 20:20:43,651] [INFO] [root.spawn:60] [PID:4476] x86_64-linux-gnu-gcc /tmp/tmprh_4fdjc/test.o -L/usr/local/cuda -L/usr/local/cuda/lib64 -lcufile -o /tmp/tmprh_4fdjc/a.out
[2025-02-28 20:20:43,701] [INFO] [root.spawn:60] [PID:4476] x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -c /tmp/tmp1o9clgd4/test.c -o /tmp/tmp1o9clgd4/test.o
[2025-02-28 20:20:43,720] [INFO] [root.spawn:60] [PID:4476] x86_64-linux-gnu-gcc /tmp/tmp1o9clgd4/test.o -laio -o /tmp/tmp1o9clgd4/a.out
/usr/local/lib/python3.11/dist-packages/axolotl/monkeypatch/relora.py:16: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import ZeroRedundancyOptimizer
[2025-02-28 20:20:47,154] [INFO] [axolotl.utils.config.models.input.check_bf16:1693] [PID:4476] [RANK:0] bf16 support detected, but not enabled for this configuration.[39m
object address  : 0x787975d3f640
object refcount : 2
object type     : 0x92bc20
object type name: OSError
object repr     : OSError("Can't load the configuration of 'meta-llama/Llama-3.2-3B'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'meta-llama/Llama-3.2-3B' is the correct path to a directory containing a config.json file")
lost sys.stderr
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.11/dist-packages/accelerate/commands/launch.py", line 1172, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.11/dist-packages/accelerate/commands/launch.py", line 762, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'axolotl.cli.train', '/content/axolotl_label.yaml']' returned non-zero exit status 1.

### Steps to reproduce

In a colab notebook run

1. !pip3 install --no-build-isolation axolotl[flash-attn,deepspeed] 
2.  Restart runtime when prompted
3. !axolotl fetch examples
4. !axolotl train examples/llama-3/lora-1b.yml

### Config yaml

```yaml
base_model: NousResearch/Llama-3.2-1B
# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: teknium/GPT4-LLM-Cleaned
    type: alpaca
dataset_prepared_path: last_run_prepared
val_set_size: 0.1
output_dir: ./outputs/lora-out

adapter: lora
lora_model_dir:

sequence_len: 2048
sample_packing: true
eval_sample_packing: true
pad_to_sequence_len: true

lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_fan_in_fan_out:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 2
micro_batch_size: 2
num_epochs: 1
optimizer: adamw_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

loss_watchdog_threshold: 5.0
loss_watchdog_patience: 3

warmup_steps: 10
evals_per_epoch: 4
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: "<|end_of_text|>"
```

### Which Operating Systems are you using?

- [ ] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11.11

### axolotl branch-commit

v0.7.0

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.
