### ISSUE TITLE
Trion 3.2.0 Doesn't Work with GRPO+vllm

### ISSUE THREAD

**Issue by RevanthRameshkumar** [axolotl-ai-cloud/axolotl#2526]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

The GRPO training as detailed in the docs should just work (launch vllm srv command and launch train command).

### Current behaviour

Instead, the axolotl commands execute, and I get a PY_SSIZE_T_CLEAN incorrectly set issue. I tried downgrading pytorch to 2.5.1 but that did nothing. Eventually what ended up working was installing axolotl in the following way (clean conda env):
```
pip3 install -U packaging==23.2 setuptools==75.8.0 wheel ninja

module load cuda/12.4
which nvcc


pip install wandb

pip3 install torch torchvision torchaudio
pip3 install --no-build-isolation --verbose axolotl[flash-attn,deepspeed,vllm]
pip install triton==3.1.0

axolotl

```

So basically I uninstall triton 3.2.0 and install 3.1.0. I still get a torch dynamo error but it doesnt kill the service and the grpo training continues.

This bug only happens with the grpo training, the example quickstsart with fetch+finetune doesn't throw any errors.

### Steps to reproduce

install axolotl as instructed on the main readme with python 3.11

### Config yaml

```yaml
base_model: Qwen/Qwen2.5-1.5B-Instruct
# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

load_in_8bit: false
load_in_4bit: false
strict: false

torch_compile: true

vllm:
    host: 0.0.0.0
    port: 8000
    tensor_parallel_size: 2
    gpu_memory_utilization: 0.85
    dtype: auto
    # max_model_len: # you may find it useful to set the vLLM model context length if you know this beforehand

rl: grpo
trl:
  use_vllm: true
  vllm_server_host: localhost
  vllm_server_port: 8000
  vllm_server_timeout: 300
  beta: 0.001
  max_completion_length: 512
  use_vllm: true
  reward_funcs:
    - gsm8k_grpo.correctness_reward_func
    - gsm8k_grpo.int_reward_func
    - gsm8k_grpo.strict_format_reward_func
    - gsm8k_grpo.soft_format_reward_func
    - gsm8k_grpo.xmlcount_reward_func
  vllm_gpu_memory_utilization: 0.9
  vllm_max_model_len: 800
  num_generations: 16

chat_template: qwen_25
datasets:
  - path: skrishna/gsm8k_only_answer
    type: gsm8k_grpo.axo_gsm8k_transform
dataset_prepared_path: /gscratch/clmbr/revr/LRMGraph/workspace/data/last_run_prepared
skip_prepare_dataset: true
val_set_size: 0.0
output_dir: /gscratch/clmbr/revr/LRMGraph/workspace/data/axolotl-artifacts/r1-outputs

dataloader_prefetch_factor: 32
dataloader_num_workers: 2
dataloader_pin_memory: true

gc_steps: 1

sequence_len: 800
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: false

wandb_project: gsm8k-grpo-proj
wandb_entity:
wandb_name: rev2021-university-of-washington

gradient_accumulation_steps: 8
micro_batch_size: 16  # should match num_generations / num_gpus
num_epochs: 1

optimizer: adamw_torch_fused
lr_scheduler: constant_with_warmup
learning_rate: 1.0e-6
max_grad_norm: 1.0
weight_decay: 0.1

bf16: true
tf32: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
flash_attention: true

logging_steps: 1
warmup_steps: 100
evals_per_epoch: 1
saves_per_epoch: 4
```

### Possible solution

downgrade triton?
I heard folks using unsloth have similar problems

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

latest published on pypi

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.
