### ISSUE TITLE
GPU VRAM requirements seem way too high

### ISSUE THREAD

**Issue by DevonPeroutky** [axolotl-ai-cloud/axolotl#2531]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I'm attempting to train Qwen2.5-coder-32B on 8xH100s (640 GB of total VRAM) and unable to perform training even on a micro_batch size of 1.

According to my calculations, a 32B parameter model, with:

- sequence_length: 4096 
- micro_batch_size: 1
- deepspeed_config: zero3_bf16_cpuoffload_all.json

should only take around 450-500GB for a single batch:

- Model Weights: 65 GB
- KV Cache: 10.00 GB
- Activation Memory: 30 GB
- Optimizer Memory: 250 GB
- Gradients Memory: 125 GB
**Total size: 480GB**

This [post from meta](https://huggingface.co/blog/llama31#training-memory-requirements) seems to suggest a 70B llama3 only needs 500GB for full weights fine-tuning

What could be the reason for 640GB not being enough for a 32B? Are my calculations/assumptions incorrect? 

### Current behaviour

```
rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 272.00 MiB. GPU 0 has a total capacity of 79.19 GiB of which 219.06 MiB is free. Including non-PyTorch memory, this process has 78.97 GiB memory in use. Of the allocated memory 74.10 GiB is allocated by PyTorch, and 503.73 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

### Steps to reproduce

axolotl train config --deepspeed zero3_bf16_cpuoffload_all.json

### Config yaml

```yaml
# -----------------------------------
# ----------- Base Model ------------
# -----------------------------------
base_model: Qwen/Qwen2.5-Coder-32B
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

# -----------------------------------
# ------------ Datasets -------------
# -----------------------------------
shuffle_merged_datasets: true

chat_template: qwen_25

datasets:
  - path: macguffin-user/repos
    type: chat_template
    split: train

    field_messages: messages
    message_field_role: role
    message_field_content: content
    roles_to_train: ["assistant"]


dataset_prepared_path: last_run_prepared_qwen2.5-coder-32b-v0
val_set_size: 0.03
output_dir: /home/ubuntu/qwen2.5-coder-32B-0.0.0

# -----------------------------------
# -------- Hyper Parameters ---------
# -----------------------------------
sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

gradient_accumulation_steps: 4
micro_batch_size: 1
num_epochs: 2
logging_steps: 1
optimizer: paged_adamw_8bit

# Learning Rate
lr_scheduler: cosine
learning_rate: 2e-6
warmup_ratio: 0.1

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
saves_per_epoch: 5
evals_per_epoch: 10
save_total_limit: 10
save_steps:
eval_sample_packing: false
debug:
deepspeed: /home/ubuntu/axolotl/deepspeed_configs/zero3_bf16_cpuoffload_all.json
weight_decay: 0.01


# Gradient clipping max norm
max_grad_norm: 1.0

fsdp:
fsdp_config:
special_tokens:
  bos_token: "<|im_start|>"
  eos_token: "<|im_end|>"
  pad_token: "<|endoftext|>"

# -----------------------------------
# --------- Weights & Biases --------
# -----------------------------------
....
```

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

v0.7.0 (latest breaks on lambda labs)

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.
