### ISSUE TITLE
Value Error, "torch_compile should be set within your deepspeed config file"

### ISSUE THREAD

**Issue by RevanthRameshkumar** [axolotl-ai-cloud/axolotl#2544]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I tried a lot of different configs/file paths and am still getting the same error
(w/ args passed in via cli and via yaml too)

im on triton 3.1.0 because I was getting other errors with 3.2.0

### Current behaviour

i get this error
```
[out, 10:26, 846s, g3118] [2025-04-21 11:26:37,216] [INFO] [datasets.<module>:54] [PID:44223] PyTorch version 2.6.0 available.
[err, 11:47, 928s, g3118] Traceback (most recent call last):
[err, 11:47, 928s, g3118]   File "/gscratch/clmbr/revr/LRMGraph/axolotl_env/bin/axolotl", line 8, in <module>
[err, 11:47, 928s, g3118]     sys.exit(main())
[err, 11:47, 928s, g3118]              ^^^^^^
[err, 11:47, 928s, g3118]   File "/gscratch/clmbr/revr/LRMGraph/axolotl_env/lib/python3.11/site-packages/axolotl/cli/main.py", line 337, in main
[err, 11:47, 928s, g3118]     cli()
[err, 11:47, 928s, g3118]   File "/gscratch/clmbr/revr/LRMGraph/axolotl_env/lib/python3.11/site-packages/click/core.py", line 1161, in __call__
[err, 11:48, 929s, g3118]     return self.main(*args, **kwargs)
[err, 11:48, 929s, g3118]            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[err, 11:48, 929s, g3118]   File "/gscratch/clmbr/revr/LRMGraph/axolotl_env/lib/python3.11/site-packages/click/core.py", line 1082, in main
[err, 11:48, 929s, g3118]     rv = self.invoke(ctx)
[err, 11:48, 929s, g3118]          ^^^^^^^^^^^^^^^^
[err, 11:48, 929s, g3118]   File "/gscratch/clmbr/revr/LRMGraph/axolotl_env/lib/python3.11/site-packages/click/core.py", line 1697, in invoke
[err, 11:48, 929s, g3118]     return _process_result(sub_ctx.command.invoke(sub_ctx))
[err, 11:48, 929s, g3118]                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[err, 11:48, 929s, g3118]   File "/gscratch/clmbr/revr/LRMGraph/axolotl_env/lib/python3.11/site-packages/click/core.py", line 1443, in invoke
[err, 11:48, 929s, g3118]     return ctx.invoke(self.callback, **ctx.params)
[err, 11:48, 929s, g3118]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[err, 11:48, 929s, g3118]   File "/gscratch/clmbr/revr/LRMGraph/axolotl_env/lib/python3.11/site-packages/click/core.py", line 788, in invoke
[err, 11:48, 929s, g3118]     return __callback(*args, **kwargs)
[err, 11:48, 929s, g3118]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[err, 11:48, 929s, g3118]   File "/gscratch/clmbr/revr/LRMGraph/axolotl_env/lib/python3.11/site-packages/axolotl/cli/utils.py", line 66, in wrapper
[err, 11:48, 929s, g3118]     return func(*args, **filtered_kwargs)
[err, 11:48, 929s, g3118]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[err, 11:48, 929s, g3118]   File "/gscratch/clmbr/revr/LRMGraph/axolotl_env/lib/python3.11/site-packages/axolotl/cli/main.py", line 330, in vllm_serve
[err, 11:48, 929s, g3118]     do_vllm_serve(config, cli_args)
[err, 11:48, 929s, g3118]   File "/gscratch/clmbr/revr/LRMGraph/axolotl_env/lib/python3.11/site-packages/axolotl/cli/vllm_serve.py", line 28, in do_vllm_serve
[err, 11:48, 929s, g3118]     cfg = load_cfg(config)
[err, 11:48, 929s, g3118]           ^^^^^^^^^^^^^^^^
[err, 11:48, 929s, g3118]   File "/gscratch/clmbr/revr/LRMGraph/axolotl_env/lib/python3.11/site-packages/axolotl/cli/config.py", line 197, in load_cfg
[err, 11:48, 929s, g3118]     cfg = validate_config(
[err, 11:48, 929s, g3118]           ^^^^^^^^^^^^^^^^
[err, 11:48, 929s, g3118]   File "/gscratch/clmbr/revr/LRMGraph/axolotl_env/lib/python3.11/site-packages/axolotl/utils/config/__init__.py", line 293,
in validate_config
[err, 11:48, 929s, g3118]     AxolotlConfigWCapabilities(
[err, 11:48, 929s, g3118]   File "/gscratch/clmbr/revr/LRMGraph/axolotl_env/lib/python3.11/site-packages/pydantic/main.py", line 214, in __init__
[err, 11:48, 929s, g3118]     validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
[err, 11:48, 929s, g3118]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[err, 11:48, 929s, g3118] pydantic_core._pydantic_core.ValidationError: 1 validation error for AxolotlConfigWCapabilities
[err, 11:48, 929s, g3118]   Value error, torch_compile should be set within your deepspeed config file [type=value_error, input_value={'base_model': 'meta-llam...orch_version': '2.6.0'}}, input_type=dict]
[err, 11:48, 929s, g3118]     For further information visit https://errors.pydantic.dev/2.10/v/value_error
[err, 12:17, 957s, g3118] /gscratch/clmbr/revr/LRMGraph/axolotl_env/lib/python3.11/site-packages/transformers/utils/hub.py:105: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
[err, 12:17, 957s, g3118]   warnings.warn(
^CDo you also want to cancel job 25492986? [y/N] ^CTraceback (most recent call last):
  File "/gscratch/clmbr/revr/LRMGraph/scripts/slurm_job_monitor.py", line 150, in main
    time.sleep(1)
```

### Steps to reproduce

cd ./scripts/axolotl/experiments/initial_rl

CUDA_VISIBLE_DEVICES=2,3 axolotl vllm-serve saparov_graph.yaml &
CUDA_VISIBLE_DEVICES=0,1 axolotl train saparov_graph.yaml --num-processes 2

### Config yaml

```yaml
base_model: meta-llama/Meta-Llama-3-8B-Instruct
# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

load_in_8bit: false
load_in_4bit: false
strict: false

torch_compile: true

vllm:
    host: 0.0.0.0
    port: 8000
    tensor_parallel_size: 2
    gpu_memory_utilization: 0.85
    dtype: auto
    # max_model_len: # you may find it useful to set the vLLM model context length if you know this beforehand

rl: grpo
trl:
  use_vllm: true
  vllm_server_host: localhost
  vllm_server_port: 8000
  vllm_server_timeout: 300
  beta: 0.001
  max_completion_length: 4096
  use_vllm: true
  reward_funcs:
    - saparov_graph.correctness_reward_func
    - saparov_graph.int_reward_func
    - saparov_graph.strict_format_reward_func
    - saparov_graph.soft_format_reward_func
    - saparov_graph.xmlcount_reward_func
  vllm_gpu_memory_utilization: 0.9
  num_generations: 16

deepspeed: /gscratch/clmbr/revr/LRMGraph/scripts/axolotl/experiments/initial_rl/deepspeed_configs/zero1_torch_compile.json

chat_template: qwen_25
datasets:
  - path: skrishna/gsm8k_only_answer
    type: saparov_graph.axo_gsm8k_transform
dataset_prepared_path: /gscratch/clmbr/revr/LRMGraph/workspace/data/last_run_prepared
skip_prepare_dataset: true
val_set_size: 0.0
output_dir: /gscratch/clmbr/revr/LRMGraph/workspace/data/axolotl-artifacts/initial-rl

dataloader_prefetch_factor: 32
dataloader_num_workers: 2
dataloader_pin_memory: true

gc_steps: 1

sequence_len: 800
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: false

# lora_modules_to_save:
#  - embed_tokens
#  - lm_head

wandb_project: gsm8k-grpo-proj
wandb_entity:
wandb_name: rev2021-university-of-washington

gradient_accumulation_steps: 8
micro_batch_size: 16  # should match num_generations / num_gpus
num_epochs: 1

optimizer: adamw_torch_fused
lr_scheduler: constant_with_warmup
learning_rate: 1.0e-6
max_grad_norm: 1.0
weight_decay: 0.1

bf16: true
tf32: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
flash_attention: true

logging_steps: 1
warmup_steps: 100
evals_per_epoch: 1
# saves_per_epoch: 4
save_steps: 200

auto_resume_from_checkpoints: true

special_tokens:
   pad_token: <|end_of_text|>
```

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

main

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.
