### ISSUE TITLE
Llama 4 Training Run Consistently Crashes During Save Step

### ISSUE THREAD

**Issue by selalipop** [axolotl-ai-cloud/axolotl#2548]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Checkpoint saved to disk

### Current behaviour

Training run crashes:

```
[rank0]:W0422 10:56:01.149000 45696 torch/distributed/checkpoint/default_planner.py:543]                     key:optimizer.state.940.exp_avg invalid fill tensor-volume:
[rank0]:W0422 10:56:01.149000 45696 torch/distributed/checkpoint/default_planner.py:543]                     655360 chunks-volume: 81920 

(several repeated "invalid fill tensor-volume" messages

...

[rank0]:   File "/home/ubuntu/venv/lib/python3.12/site-packages/torch/distributed/checkpoint/state_dict_saver.py", line 313, in global_step
[rank0]:     all_local_plans, global_metadata = planner.create_global_plan(all_local_plans)
[rank0]:                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/venv/lib/python3.12/site-packages/torch/distributed/checkpoint/default_planner.py", line 125, in create_global_plan
[rank0]:     raise ValueError("Failed to validate global plan")
[rank0]: ValueError: Failed to validate global plan
```

Unsure if related but during setup there are warning about shared memory:
```
  triton_flex_attention_backward_33 64.4875 ms 58.3% BLOCKS_ARE_CONTIGUOUS=False, BLOCK_M1=64, BLOCK_M2=64, BLOCK_N1=64, BLOCK_N2=64, FLOAT32_PRECISION="'tf32'", GQA_SHARED_HEADS=1, HAS_FULL_BLOCKS=True, IS_DIVISIBLE=False, OUTPUT_LOGSUMEXP=True, PRESCALE_QK=False, QK_HEAD_DIM=128, ROWS_GUARANTEED_SAFE=False, SM_SCALE=0.08838834764831845, SPARSE_KV_BLOCK_SIZE=128, SPARSE_Q_BLOCK_SIZE=128, V_HEAD_DIM=128, num_stages=3, num_warps=4
SingleProcess AUTOTUNE benchmarking takes 13.9948 seconds and 0.2249 seconds precompiling for 20 choices

--->**[rank4]:W0422 11:03:55.855000 53380 torch/_inductor/select_algorithm.py:1696] [1/0] out of resource: shared memory, Required: 237824, Hardware limit: 232448. Reducing block sizes or `num_stages` may help.**

AUTOTUNE flex_attention_backward(2x40x15040x128, 2x40x15040x128, 2x40x15040x128, 2x40x15040, 2x40x15040, 2x40x15040x128, 2x40x15040x128, 2x40x15040x128, 2x1x118, 2x1x118x118, 2x1x118, 2x1x118x118, 2x1x118, 2x1x118x118, 2x1x118, 2x1x118x118, , 2x15040, 2x15040, 2x15040)
```

### Steps to reproduce

Llama 4 on 8xH200 with default example as a base

axolotl: latest main
torch: 2.6.0
bitsandbytes: 0.45.4

### Config yaml

```yaml
base_model: axolotl-quants/Llama-4-Scout-17B-16E-Linearized-bnb-nf4-bf16
model_type: Llama4ForConditionalGeneration

plugins:
  - axolotl.integrations.liger.LigerPlugin

liger_glu_activation: true
liger_rms_norm: true
liger_layer_norm: true

llama4_linearized_experts: true
load_in_4bit: true
adapter: qlora
lora_r: 128
lora_alpha: 256
lora_target_modules:
  - self_attn.q_proj
  - self_attn.k_proj
  - self_attn.v_proj
  - self_attn.o_proj
  - shared_expert.gate_proj
  - shared_expert.up_proj
  - shared_expert.down_proj
  # - experts.gate_projs.[0-9]+$
  # - experts.up_projs.[0-9]+$
  # - experts.down_projs.[0-9]+$
lora_modules_to_save:
  # - lm_head
  # - embed_tokens

chat_template: llama4
datasets:
  - path: complete.jsonl
    type: chat_template
    chat_template: tokenizer_default
    data_files: complete.jsonl

dataset_prepared_path: data/last_run_prepared

val_set_size: 0.01
output_dir: ./outputs/out

sequence_len: 15000
sample_packing: false
pad_to_sequence_len: true

gradient_accumulation_steps: 1
micro_batch_size: 2
num_epochs: 2
optimizer: adamw_torch_4bit
lr_scheduler: cosine
learning_rate: 2e-4
train_on_inputs: false
bf16: true
tf32: true

logging_steps: 1
flex_attention: true
flex_attn_compile_kwargs:
  dynamic: false
  mode: max-autotune-no-cudagraphs

warmup_steps: 100
evals_per_epoch: 10
#saves_per_epoch: 20
save_steps: 2
weight_decay: 0.01

fsdp:
  - auto_wrap
  - full_shard

fsdp_config:
  fsdp_version: 2
  fsdp_offload_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: Llama4TextDecoderLayer
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_reshard_after_forward: true
  fsdp_activation_checkpointing: true
special_tokens:
  pad_token: <|finetune_right_pad_id|>
  eos_token: <|eot|>

wandb_project: project
wandb_name: name
wandb_log_model: checkpoint
torch_compile: false # Tried as an attempted fix, didn't save when true
```

### Possible solution

Could be related to bnb version? Needed latest due to a bug: https://github.com/bitsandbytes-foundation/bitsandbytes/issues/1584

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.12

### axolotl branch-commit

main/7651550850b7c8d0420bbf8354b6e3dd2728493b

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.
