### ISSUE TITLE
Running inference of QLoRA fine-tuned Llama-4 Scout does not work

### ISSUE THREAD

**Issue by cyril-k** [axolotl-ai-cloud/axolotl#2550]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Fine-tuned quantized Llama-4 Scout model should work with inference engines like vLLM. If any additional steps to merge or de-linearize model are required, they should be documented/tested as in current state de-linearization script does not seem to work.

### Current behaviour

Fine-tuned Llama-4 Scout (merged base model + QLoRA adapter) after fine-tuning with [this example](https://github.com/axolotl-ai-cloud/axolotl/blob/main/examples/llama-4/scout-qlora-single-h100-flex.yaml) does not work with vLLM, error: `ValueError: Unsupported bnb_4bit_quant_storage: bfloat16`

Suggested [script to de-linearize model](https://github.com/axolotl-ai-cloud/axolotl/blob/main/src/axolotl/cli/delinearize_llama4.py) does not seem to work, as some model weights are not converted correctly.

See output attached: [output-delinearize-error.txt](https://github.com/user-attachments/files/19857428/output-delinearize-error.txt)

### Steps to reproduce

- Install torch 2.6.0 and axolotl from main branch on an instance with a single H100
- Download [this example config](https://github.com/axolotl-ai-cloud/axolotl/blob/main/examples/llama-4/scout-qlora-single-h100-flex.yaml)
- Run fine-tuning with `axolotl train scout-qlora-single-h100-flex.yaml`
- Merge adapter into base model with `axolotl merge-lora scout-qlora-single-h100-flex.yaml --lora-model-dir="outputs/out"`
- Attempt to run inference with `vllm serve outputs/out/merged`

---

- To attempt de-linearization: I had to patch the script [here](https://github.com/axolotl-ai-cloud/axolotl/blob/32e335dd51fa310e39f01dcaf58fcb90c2c94be1/src/axolotl/cli/delinearize_llama4.py#L119) with `model_.to("cpu")` to avoid getting CUDA OOM on a single H100.
- To run de-linearization: `PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True axolotl delinearize-llama4 ./outputs/out/merged ./outputs/delinearized`

### Config yaml

```yaml
base_model: axolotl-quants/Llama-4-Scout-17B-16E-Linearized-bnb-nf4-bf16
model_type: Llama4ForConditionalGeneration
# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

plugins:
  - axolotl.integrations.liger.LigerPlugin
  - axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin

liger_glu_activation: true
liger_rms_norm: true
liger_layer_norm: true
cut_cross_entropy: true

llama4_linearized_experts: true  # needed with custom linearized experts model
load_in_4bit: true
adapter: qlora
lora_r: 32
lora_alpha: 64
lora_target_modules:
  - self_attn.q_proj
  - self_attn.k_proj
  - self_attn.v_proj
  - self_attn.o_proj
  - shared_expert.gate_proj
  - shared_expert.up_proj
  - shared_expert.down_proj
  # - experts.gate_projs.[0-9]+$  # optionally train the moe experts
  # - experts.up_projs.[0-9]+$
  # - experts.down_projs.[0-9]+$
lora_modules_to_save:
  # - lm_head  # needed if modifying vocabulary
  # - embed_tokens

lora_mlp_kernel: true
lora_qkv_kernel: true
lora_o_kernel: true

chat_template: llama4
datasets:
  - path: mlabonne/FineTome-100k
    type: chat_template
    split: train[:20%]
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value

dataset_prepared_path: last_run_prepared
val_set_size: 0.0
output_dir: ./outputs/out

sequence_len: 4096  # up to 8k will work on a single H100
sample_packing: true
pad_to_sequence_len: true

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_torch_4bit
lr_scheduler: cosine
learning_rate: 1e-4

bf16: true
tf32: true

torch_compile: true
flex_attention: true
flex_attn_compile_kwargs:
  dynamic: false
  mode: max-autotune-no-cudagraphs

gradient_checkpointing: offload
gradient_checkpointing_kwargs:
  use_reentrant: false

logging_steps: 1
warmup_steps: 20
evals_per_epoch: 1
saves_per_epoch: 1

weight_decay: 0.0
special_tokens:
  pad_token: <|finetune_right_pad_id|>
  eos_token: <|eot|>
```

### Possible solution

Correct de-linearization script to avoid OOMs on a single H100 as well as to convert fine-tuned model to useable format as currently it does not work.

Provide an end-to-end example on running inference of fine-tuned model for [this example config](https://github.com/axolotl-ai-cloud/axolotl/blob/main/examples/llama-4/scout-qlora-single-h100-flex.yaml) with a popular inference engine like vLLM.

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main/32e335d

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.
