### ISSUE TITLE
Bug in importing reward function from module

### ISSUE THREAD

**Issue by dhruvmullick** [axolotl-ai-cloud/axolotl#2557]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Successfully import reward function from module, even if the reward function is present in a module which is inside another package (i.e. A.B.reward_fn)

### Current behaviour

The import step fails, failing the TRL training routine

### Steps to reproduce

Have the reward function in a module present inside another package e.g. here the reward function (```strict_format_reward_func```) is present inside the module ```code_based``` which is present inside another package (```rewards```) 

(see config for example of reward function path) 

Error seen: 

```
[2025-04-24 17:22:19,323] [INFO] [axolotl.get_reward_func:147] [PID:6666] [RANK:1] Reward function rewards.code_based.strict_format_reward_func is a pre-trained model path - if this is unexpected, please check the reward function path.
[rank1]: Traceback (most recent call last):
[rank1]:   File "/opt/conda/lib/python3.11/site-packages/axolotl/core/trainers/grpo/__init__.py", line 138, in get_reward_func
[rank1]:     reward_func_module = importlib.import_module(reward_func_fqn.split(".")[-2])
[rank1]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/opt/conda/lib/python3.11/importlib/__init__.py", line 126, in import_module
[rank1]:     return _bootstrap._gcd_import(name[level:], package, level)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
[rank1]:   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
[rank1]:   File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
[rank1]: ModuleNotFoundError: No module named 'code_based'
```

### Config yaml

```yaml
rl: grpo
trl:
  use_vllm: true
  vllm_server_host: 0.0.0.0
  vllm_server_port: 8000
  vllm_server_timeout: 300
  vllm_enable_prefix_caching: true
  beta: 0.001
  max_completion_length: 256
  num_generations: 8
  reward_funcs: ["rewards.code_based.strict_format_reward_func"] # format: '{file_name}.{fn_name}'
  reward_weights: [1.0]
```

### Possible solution

In the snippet: 

https://github.com/axolotl-ai-cloud/axolotl/blob/1447beb1328f8298ae0b7333091609f895fc596e/src/axolotl/core/trainers/grpo/__init__.py#L137-L139

```reward_func_module = importlib.import_module(reward_func_fqn.split(".")[-2])```

should be changed to 

```reward_func_module = importlib.import_module('.'.join(reward_func_fqn.split(".")[:-1]))```

### Which Operating Systems are you using?

- [x] Linux
- [x] macOS
- [ ] Windows

### Python Version

3.11.10

### axolotl branch-commit

version 0.8.1

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.
