### ISSUE TITLE
Gemma 3 Multi-Image Training Error: ValueError - Image token/count mismatch (`Prompt contained X image tokens but received Y images`)

### ISSUE THREAD

**Issue by rdzotz** [axolotl-ai-cloud/axolotl#2567]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

---

Hi Axolotl Team/Community,

I'm encountering a `ValueError` when trying to fine-tune `google/gemma-3-4b-it` using a dataset that contains **multiple images per prompt**. The training fails during the data collation step.

**Problem:**

The training process throws the following error shortly after starting:

```
ValueError: Prompt contained 2 image tokens but received 1 images.
```

This error originates from the `Gemma3Processor` when `apply_chat_template` is called within the `axolotl.utils.collators.mm_chat.process_rows` function.

**(Optional: Add Full Traceback Here)**
```
<Include the full traceback you shared earlier here>
```

**Setup:**

*   **Model:** `google/gemma-3-4b-it`
*   **Processor:** `AutoProcessor` (implicitly loading `Gemma3Processor`)
*   **Dataset:**
    *   Pre-processed and saved to disk using `datasets.save_to_disk()` (Arrow format).
    *   The dataset structure includes:
        *   `messages`: A list of dictionaries following the chat template format (e.g., `{'role': 'user', 'content': [{'type': 'text', ...}, {'type': 'image', 'index': 0}, {'type': 'image', 'index': 1}]}`).
        *   `images`: A list containing the corresponding PIL Image objects loaded from absolute paths.
    *   Crucially, examples contain **multiple** image placeholders in `messages` and multiple PIL images in the `images` list.
*   **Axolotl Config Snippet (`datasets` section):**
    ```yaml
    base_model: google/gemma-3-4b-it
    processor_type: AutoProcessor
    chat_template: gemma3
    # ... other config ...
    datasets:
      - path: /path/to/your/processed_arrow_format # Path to the saved Arrow dataset
        type: chat_template # Axolotl loads Arrow format automatically when path is a directory
        split: train
        field_messages: messages
    # ... rest of config ...
    ```

**Troubleshooting & Verification Steps:**

1.  **Data Integrity Check:** I loaded the final Arrow dataset (`processed_arrow_format`) directly using `datasets.load_from_disk()`. I verified that for each example, the number of `{'type': 'image', 'index': N}` entries in the `messages` list **exactly matches** the number of PIL Image objects present in the `images` list. The data structure appears correct in the saved Arrow files.
2.  **Manual Image Loading Check:** Before saving to Arrow, I iterated through all image paths referenced in the intermediate JSONL file and confirmed they could be successfully opened and loaded using `PIL.Image.open(path).load()` without errors.
3.  **Single-Image Test:** I modified the data preparation pipeline (`scripts/transform_dataset.py` and `scripts/preprocess_and_save.py`) to create a version of the dataset containing only the *first* image placeholder and the *first* PIL image for each example. When I pointed the Axolotl config to this single-image dataset (`processed_arrow_format_single`), the training **started successfully** without the `ValueError`.

**Conclusion:**

Since the saved Arrow data appears structurally correct and the training works fine with single-image examples, the issue seems specific to how Axolotl's data collator (`mm_chat.py`) or its interaction with the `Gemma3Processor` handles examples with **multiple images** during the batching/`apply_chat_template` process. It appears to be losing or miscounting images before passing them to the processor.

**Question:**

Is this a known issue with multi-image training for Gemma 3 in Axolotl? Are there any known workarounds or configuration adjustments needed? I also noticed something similar with TRL here https://github.com/huggingface/trl/issues/3121?utm_source=chatgpt.com

### Current behaviour

The training process fails early during data collation. When processing an example that contains multiple image placeholders (e.g., 2) in the messages structure, the Gemma3Processor.apply_chat_template function raises a ValueError. The error message indicates a mismatch between the number of expected image tokens found in the prompt and the number of actual images received by the processor (e.g., ValueError: Prompt contained 2 image tokens but received 1 images.). This suggests that the data collator (axolotl.utils.collators.mm_chat.py) is not correctly passing the full list of images from the dataset example to the processor when multiple images are present.

### Steps to reproduce

1.  **Prepare Minimal Raw Data:**
    *   Create a directory for raw data, e.g., `data/raw/`.
    *   Create a subdirectory for images: `data/raw/images/`.
    *   Create two small placeholder image files (e.g., simple PNGs): `data/raw/images/image1.png` and `data/raw/images/image2.png`.
    *   Create a minimal `metadata.jsonl` file in `data/raw/` containing at least one line representing a multi-image prompt:
        ```json
        {"area_id": "test01", "human_annotated": "true", "source_ref": ["s3://placeholder-bucket/images/image1.png", "s3://placeholder-bucket/images/image2.png"], "hours_delta": 24, "collection_times": ["2024-01-01T10:00:00Z", "2024-01-02T10:00:00Z"], "start_date": "2024-01-01", "end_date": "2024-01-02", "bbox": [0, 0, 1, 1], "title": "Test Location", "region": "Test Region", "use_case": "Test Case", "additional_context": "Describe changes between the two images.", "assistant_response": "Image 2 shows minor differences compared to Image 1."}
        ```
    *   Create the target directory for processed data, e.g., `data/processed/`.

2.  **Run Transformation Script:** (Generate intermediate JSONL with absolute paths)
    *   Execute `scripts/transform_dataset.py` using an absolute path for the output directory. Replace `/path/to/your/project/data/processed` with the actual absolute path.
    ```bash
    # Define absolute path to the target processed data directory
    ABS_DATA_DIR="/path/to/your/project/data/processed" 
    mkdir -p "$ABS_DATA_DIR" # Ensure directory exists

    python scripts/transform_dataset.py \
      --s3-base-uri "s3://placeholder-bucket/" \
      --dataset-dir "$ABS_DATA_DIR" \
      ./data/raw/metadata.jsonl \
      "$ABS_DATA_DIR/intermediate.jsonl"
    ```
    *   Verify that `$ABS_DATA_DIR/intermediate.jsonl` is created and contains absolute paths in the `images` list (e.g., `["/path/to/your/project/data/processed/images/image1.png", "/path/to/your/project/data/processed/images/image2.png"]`).

3.  **Run Pre-processing Script:** (Save to Arrow format)
    *   Execute `scripts/preprocess_and_save.py`:
    ```bash
    # Define absolute path to the target processed data directory (same as above)
    ABS_DATA_DIR="/path/to/your/project/data/processed"
    FINAL_ARROW_DIR="$ABS_DATA_DIR/arrow_format"

    python scripts/preprocess_and_save.py \
      "$ABS_DATA_DIR/intermediate.jsonl" \
      "$FINAL_ARROW_DIR"
    ```
    *   Verify the Arrow dataset directory (`$FINAL_ARROW_DIR`) is created.

4.  **Create Minimal Axolotl Config (`minimal_config.yml`):**
    ```yaml
    base_model: google/gemma-3-4b-it
    processor_type: AutoProcessor
    chat_template: gemma3

    # Use absolute path to the final Arrow dataset
    datasets:
      - path: /path/to/your/project/data/processed/arrow_format # <-- Update this path
        type: chat_template
        split: train
        field_messages: messages

    # Minimal training settings
    sequence_len: 512 # Keep short for quick test
    output_dir: ./minimal-output
    gradient_accumulation_steps: 1
    micro_batch_size: 1
    num_epochs: 1
    optimizer: adamw_bnb_8bit
    lr_scheduler: constant
    learning_rate: 1e-6
    bf16: true # Or fp16 depending on hardware
    tf32: true
    logging_steps: 1
    # Disable LoRA/adapter for simplicity if needed
    # adapter: 
    ```
    *   Replace `/path/to/your/project/data/processed/arrow_format` with the correct absolute path from step 3.

5.  **Run Axolotl Training:**
    ```bash
    accelerate launch -m axolotl.cli.train minimal_config.yml
    # Or: python -m axolotl.cli.train minimal_config.yml
    ```

6.  **Observe Error:** The training process should start, attempt to load and collate the data, and then fail with the `ValueError: Prompt contained 2 image tokens but received 1 images.` traceback.

### Config yaml

```yaml

```

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

main

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.
