### ISSUE TITLE
Not able to run evaluate

### ISSUE THREAD

**Issue by locovamos** [axolotl-ai-cloud/axolotl#2585]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I need to evaluate my finetuned model by using evaluate command.

### Current behaviour

I'm getting always the following when executing the evaluate:

Traceback (most recent call last):
  File "/home/axolotl-test/axolotl/bin/axolotl", line 8, in <module>
    sys.exit(main())
  File "/home/axolotl-test/axolotl/lib/python3.10/site-packages/axolotl/cli/main.py", line 337, in main
    cli()
  File "/home/axolotl-test/axolotl/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/axolotl-test/axolotl/lib/python3.10/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/axolotl-test/axolotl/lib/python3.10/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/axolotl-test/axolotl/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/axolotl-test/axolotl/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/axolotl-test/axolotl/lib/python3.10/site-packages/axolotl/cli/utils.py", line 66, in wrapper
    return func(*args, **filtered_kwargs)
  File "/home/axolotl-test/axolotl/lib/python3.10/site-packages/axolotl/cli/main.py", line 212, in evaluate
    do_cli(config=config, **kwargs)
  File "/home/axolotl-test/axolotl/lib/python3.10/site-packages/axolotl/cli/evaluate.py", line 59, in do_cli
    do_evaluate(parsed_cfg, parsed_cli_args)
  File "/home/axolotl-test/axolotl/lib/python3.10/site-packages/axolotl/cli/evaluate.py", line 42, in do_evaluate
    evaluate(cfg=cfg, dataset_meta=dataset_meta)
  File "/home/axolotl-test/axolotl/lib/python3.10/site-packages/axolotl/evaluate.py", line 104, in evaluate
    trainer = setup_trainer(
  File "/home/axolotl-test/axolotl/lib/python3.10/site-packages/axolotl/utils/trainer.py", line 630, in setup_trainer
    return trainer_builder.build(total_num_steps)
  File "/home/axolotl-test/axolotl/lib/python3.10/site-packages/axolotl/core/trainer_builder.py", line 839, in build
    trainer = trainer_cls(
  File "/home/axolotl-test/axolotl/lib/python3.10/site-packages/axolotl/core/trainers/base.py", line 64, in __init__
    super().__init__(*_args, **kwargs)
  File "/home/axolotl-test/axolotl/lib/python3.10/site-packages/transformers/utils/deprecation.py", line 172, in wrapped_func
    return func(*args, **kwargs)
  File "/home/axolotl-test/axolotl/lib/python3.10/site-packages/transformers/trainer.py", line 614, in __init__
    self._move_model_to_device(model, args.device)
  File "/home/axolotl-test/axolotl/lib/python3.10/site-packages/transformers/trainer.py", line 901, in _move_model_to_device
    model = model.to(device)
AttributeError: 'tuple' object has no attribute 'to'

### Steps to reproduce

1. Use the Qwen2.5-1.5b-Instruct Model (download it on your device)
2. Use any alpaca dataset(download it on your device) and use one of the yaml shown in examples on the github
3. Deactivate flash-attention and do not use accelerate or connections with huggingface
4. Do a training (it will work)
5. Execute evaluate in CLI (it will fail)

### Config yaml

```yaml
base_model: ./Qwen2.5-1.5B-Instruct

trust_remote_code: false

load_in_8bit: true
load_in_4bit: false
strict: false

datasets:
  - path: ./alpaca_dataset.jsonl
    type: alpaca

dataset_exact_deduplication: true

sequence_len: 2048
sample_packing: false
pad_to_sequence_len:

dataset_prepared_path:

adapter: lora
lora_model_dir:
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true

gradient_accumulation_steps: 2
micro_batch_size: 1
num_epochs: 3
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 0.0002
# max_grad_norm: 2

bf16: auto
tf32: false

gradient_checkpointing: false
resume_from_checkpoint:
logging_steps: 1
flash_attention: false

warmup_steps: 10
evals_per_epoch: 6
saves_per_epoch: 1
weight_decay: 0.01
```

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10.12

### axolotl branch-commit

NaN

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.
