### ISSUE TITLE
loss() Expected a value of type 'int' for argument 'num_items_in_batch' but instead found type 'NoneType'.

### ISSUE THREAD

**Issue by sankexin** [axolotl-ai-cloud/axolotl#2682]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Knowledge Distillation qwen3, train normally.

### Current behaviour

when val, num_items_in_batch will be None, then error get in topk_kd_loss:

{'loss': 22.0832, 'grad_norm': 15.678300857543945, 'learning_rate': 0.0, 'epoch': 0.05}
  5%|█████████▉                                                                                                                                                                                                      | 1/21 [01:11<23:45, 71.27s/it][2025-05-16 07:32:55,264] [INFO] [axolotl.utils.samplers.multipack.calc_min_len:434] [PID:3008] [RANK:0] gather_len_batches: [20, 20, 20, 20]
num_items_in_batch:  None
num_items_in_batch:  None
num_items_in_batch:  None
num_items_in_batch:  None
[rank2]: Traceback (most recent call last):
[rank2]:   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank2]:     return _run_code(code, main_globals, None,
[rank2]:   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[rank2]:     exec(code, run_globals)
[rank2]:   File "/home/axolotl/src/axolotl/cli/train.py", line 124, in <module>
[rank2]:     fire.Fire(do_cli)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 135, in Fire
[rank2]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 468, in _Fire
[rank2]:     component, remaining_args = _CallAndUpdateTrace(
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 684, in _CallAndUpdateTrace
[rank2]:     component = fn(*varargs, **kwargs)
[rank2]:   File "/home/axolotl/src/axolotl/cli/train.py", line 98, in do_cli
[rank2]:     return do_train(parsed_cfg, parsed_cli_args)
[rank2]:   File "/home/axolotl/src/axolotl/cli/train.py", line 54, in do_train
[rank2]:     model, tokenizer, trainer = train(cfg=cfg, dataset_meta=dataset_meta)
[rank2]:   File "/home/axolotl/src/axolotl/train.py", line 550, in train
[rank2]:     execute_training(cfg, trainer, resume_from_checkpoint)
[rank2]:   File "/home/axolotl/src/axolotl/train.py", line 216, in execute_training
[rank2]:     trainer.train(resume_from_checkpoint=resume_from_checkpoint)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2245, in train
[rank2]:     return inner_training_loop(
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2627, in _inner_training_loop
[rank2]:     self._maybe_log_save_evaluate(
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 3096, in _maybe_log_save_evaluate
[rank2]:     metrics = self._evaluate(trial, ignore_keys_for_eval)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 3045, in _evaluate
[rank2]:     metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 4154, in evaluate
[rank2]:     output = eval_loop(
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 4348, in evaluation_loop
[rank2]:     losses, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 4564, in prediction_step
[rank2]:     loss, outputs = self.compute_loss(model, inputs, return_outputs=True)
[rank2]:   File "/home/axolotl/src/axolotl/integrations/kd/trainer.py", line 89, in compute_loss
[rank2]:     loss_kd = topk_kd_loss(
[rank2]: RuntimeError: loss() Expected a value of type 'int' for argument 'num_items_in_batch' but instead found type 'NoneType'.
[rank2]: Position: 4
[rank2]: Value: None
[rank2]: Declaration: loss(Tensor student_logits, Tensor target_token_ids, Tensor target_logprobs, Tensor target_mask, int num_items_in_batch=-1, float kd_temperature=1., int top_k_before_softmax=0) -> Tensor
[rank2]: Cast error details: Unable to cast Python instance of type <class 'NoneType'> to C++ type '?' (#define PYBIND11_DETAILED_ERROR_MESSAGES or compile in debug mode for details)



and another error, if I set "torch_compile: True", then will get some fuse error.

### Steps to reproduce

axolotl train examples/qwen3/qlora-fsdp-kd_qwen3-8b.yaml

### Config yaml

```yaml
# examples/qwen3/qlora-fsdp-kd_qwen3-8b.yaml:


base_model: Qwen/Qwen3-8B
# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

plugins:
  - axolotl.integrations.kd.KDPlugin
kd_trainer: True
kd_ce_alpha: 0.1
kd_alpha: 0.9
kd_temperature: 1.0

torch_compile: False  # torch>=2.5.1, recommended to reduce vram

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: axolotl-ai-co/evolkit-logprobs-pipeline-75k-v2-sample
    type: axolotl.integrations.kd.chat_template
    field_messages: "messages_combined"
    logprobs_field: "llm_text_generation_vllm_logprobs"  # for kd only, field of logprobs
dataset_prepared_path:
val_set_size: 0.05
output_dir: ./outputs/out

sequence_len: 2048
sample_packing: true
eval_sample_packing: true
pad_to_sequence_len: true

adapter: qlora
lora_model_dir:
lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target_linear: true

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_torch_fused # adamw_torch
lr_scheduler: cosine
learning_rate: 0.0002

bf16: auto
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:                                                                                                                                                                                                                      
  use_reentrant: false                                                                                                                                                                                                                              
resume_from_checkpoint:                                                                                                                                                                                                                             
logging_steps: 1                                                                                                                                                                                                                                    
flash_attention: true                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                    
warmup_steps: 10                                                                                                                                                                                                                                    
evals_per_epoch: 4                                                                                                                                                                                                                                  
saves_per_epoch: 1                                                                                                                                                                                                                                  
weight_decay: 0.0                                                                                                                                                                                                                                   
fsdp:                                                                                                                                                                                                                                               
  - full_shard                                                                                                                                                                                                                                      
  - auto_wrap                                                                                                                                                                                                                                       
fsdp_config:                                                                                                                                                                                                                                        
  fsdp_limit_all_gathers: true                                                                                                                                                                                                                      
  fsdp_sync_module_states: true                                                                                                                                                                                                                     
  fsdp_offload_params: true                                                                                                                                                                                                                         
  fsdp_use_orig_params: false                                                                                                                                                                                                                       
  fsdp_cpu_ram_efficient_loading: true                                                                                                                                                                                                              
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP                                                                                                                                                                                                     
  fsdp_transformer_layer_cls_to_wrap: Qwen3DecoderLayer                                                                                                                                                                                             
  fsdp_state_dict_type: FULL_STATE_DICT                                                                                                                                                                                                             
  fsdp_sharding_strategy: FULL_SHARD                                                                                                                                                                                                                
special_tokens:
```

### Possible solution

error only in val stage, if I set num_items_in_batch=-1 in val stage ,then loss well be negative, like this:
```
1111111111111111111num_items_in_batch:  -1
1111111111111111111num_items_in_batch:  -1
1111111111111111111num_items_in_batch:  -1
1111111111111111111num_items_in_batch:  -1
                                                                                                                                                                                                                                                   1111111111111111111num_items_in_batch:  -1                                                                                                                                                                                           | 0/5 [00:00<?, ?it/s]
1111111111111111111num_items_in_batch:  -1
1111111111111111111num_items_in_batch:  -1
1111111111111111111num_items_in_batch:  -1
                                                                                                                                                                                                                                                   1111111111111111111num_items_in_batch:  -1█████████████████████████████████████████████████████▌                                                                                                                             | 2/5 [00:03<00:05,  1.68s/it]
1111111111111111111num_items_in_batch:  -1
1111111111111111111num_items_in_batch:  -1
1111111111111111111num_items_in_batch:  -1
                                                                                                                                                                                                                                                   1111111111111111111num_items_in_batch: 1111111111111111111num_items_in_batch:  -1████████████████████████████████████████████████████████▍                                                                                   | 3/5 [00:07<00:05,  2.55s/it]
 -1
1111111111111111111num_items_in_batch: 1111111111111111111num_items_in_batch:  -1
 -1
                                                                                                                                                                                                                                                   1111111111111111111num_items_in_batch:  -1█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                         | 4/5 [00:08<00:02,  2.19s/it]
1111111111111111111num_items_in_batch:  -1
1111111111111111111num_items_in_batch:  -1
1111111111111111111num_items_in_batch:  -1
{'eval_loss': -122.02571868896484, 'eval_runtime': 12.0105, 'eval_samples_per_second': 3.081, 'eval_steps_per_second': 0.833, 'epoch': 0.05}
```

so, how to solve ?


### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main/c0a0c75  

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.
