### ISSUE TITLE
Specified local .jsonl, but axolotl tries to load dataset from HuggingFace

### ISSUE THREAD

**Issue by mashdragon** [axolotl-ai-cloud/axolotl#2709]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Axolotl uses my local `mydata.jsonl` file and does not try to fetch from HuggingFace.

### Current behaviour

I get this error:

```
huggingface_hub.errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-)

Repository Not Found for url: https://huggingface.co/datasets/json/resolve/main/mydata.jsonl.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated. For more details, see https://huggingface.co/docs/huggingface_hub/authentication
Invalid username or password.
```

Why is axolotl trying to get my dataset file from HuggingFace?

The [docs](https://docs.axolotl.ai/docs/config.html) specifically say to use `ds_type: json` and set `path` to '"json" for local dataset'.

### Steps to reproduce

```
CUDA_VISIBLE_DEVICES="" python -m axolotl.cli.preprocess myconfig.yml
```

### Config yaml

```yaml
base_model: /mydat/Mistral-Small-3.1-24B-Instruct-2503
# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

load_in_8bit: false
load_in_4bit: true
strict: false

eot_tokens:
  - "[/INST]"

chat_template: mistral_v7_tekken
datasets:
  - path: json
    data_files: mydata.jsonl
    type: chat_template
    chat_template: tokenizer_default
    ds_type: json
    split: train
    field_messages: conversation
    message_property_mappings:
      role: from
      content: content

dataset_prepared_path: last_run_prepared
val_set_size: 0
output_dir: /myoutputdir

adapter: qlora
lora_model_dir:

sequence_len: 2048
sample_packing: true
eval_sample_packing: true
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_fan_in_fan_out:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

loss_watchdog_threshold: 5.0
loss_watchdog_patience: 3

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: "<|end_of_text|>"
```

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10.12

### axolotl branch-commit

main/5f8f8172005543e2fff728c81fd7314be7883d6f

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by mashdragon** [comment]
I had to go into the code (shared.py) to debug it myself. I changed `path` to `mydata.jsonl` and removed the `data_files` key and it's able to load now. This `path`/`data_files` thing has always been extremely confusing and needs to be made clear why there is a difference.

I think the bug is `path: json` isn't recognized.

**Comment by NanoCode012** [comment]
Hey! We have dropped support for this method of loading a while back. We currently recommend it via

```yaml
datasets:
  - path: /path/to/your/file.jsonl
    ds_type: json  # optional, auto infers from path type
```

I felt like I made a PR to address this in the docs but couldn't find it anymore. https://docs.axolotl.ai/docs/dataset_loading.html#files (See second block, I didn't merge the removal of first block)

Secondly, we also recommend using `axolotl preprocess config.yaml` instead of the old method of running. https://docs.axolotl.ai/docs/cli.html

**Comment by mashdragon** [comment]
Thanks! The part in the docs that still refers to it is `config.qmd`:

>   \# HuggingFace dataset repo | s3://,gs:// path | "json" for local dataset, make sure to fill data_files

I would make a PR but I don't know if the relationship with `data_files` has changed or how to use multiple local .jsonl files when specifying the path variable.

**Comment by NanoCode012** [comment]
Thanks for catching that. I'll make the update in the PR as well.

> I would make a PR but I don't know if the relationship with data_files has changed or how to use multiple local .jsonl files when specifying the path variable.

To use multiple, you can just specify multiple paths.

```yaml
datasets:
  - path: /path/to/your/fileA.jsonl

  - path: /path/to/your/fileB.jsonl

```

It was reported the method we initially specified (the one you used) stopped working sometime ago, and hence, we chose to keep this newer method only to prevent confusion and multiple ways of doing the same thing.
