### ISSUE TITLE
for grpo , TypeError: None is not a callable object

### ISSUE THREAD

**Issue by sankexin** [axolotl-ai-cloud/axolotl#2740]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

train grpo or dapo , qwen3

### Current behaviour

```
[2025-05-29 08:49:00,092] [WARNING] [axolotl.prompt_strategies.base.load:33] [PID:4859] [RANK:0] unable to load strategy .gsm8k_grpo
[rank0]: Traceback (most recent call last):
[rank0]:   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/home/axolotl/src/axolotl/cli/train.py", line 125, in <module>
[rank0]:     fire.Fire(do_cli)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 135, in Fire
[rank0]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 468, in _Fire
[rank0]:     component, remaining_args = _CallAndUpdateTrace(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 684, in _CallAndUpdateTrace
[rank0]:     component = fn(*varargs, **kwargs)
[rank0]:   File "/home/axolotl/src/axolotl/cli/train.py", line 99, in do_cli
[rank0]:     return do_train(parsed_cfg, parsed_cli_args)
[rank0]:   File "/home/axolotl/src/axolotl/cli/train.py", line 51, in do_train
[rank0]:     dataset_meta = load_preference_datasets(cfg=cfg, cli_args=cli_args)
[rank0]:   File "/home/axolotl/src/axolotl/common/datasets.py", line 133, in load_preference_datasets
[rank0]:     train_dataset, eval_dataset = load_prepare_preference_datasets(cfg)
[rank0]:   File "/home/axolotl/src/axolotl/utils/data/rl.py", line 201, in load_prepare_preference_datasets
[rank0]:     train_dataset = load_split(cfg.datasets, cfg)
[rank0]:   File "/home/axolotl/src/axolotl/utils/data/rl.py", line 152, in load_split
[rank0]:     split_datasets[i] = map_dataset(
[rank0]:   File "/home/axolotl/src/axolotl/utils/data/rl.py", line 63, in map_dataset
[rank0]:     sig = inspect.signature(ds_transform_fn)
[rank0]:   File "/usr/lib/python3.10/inspect.py", line 3254, in signature
[rank0]:     return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
[rank0]:   File "/usr/lib/python3.10/inspect.py", line 3002, in from_callable
[rank0]:     return _signature_from_callable(obj, sigcls=cls,
[rank0]:   File "/usr/lib/python3.10/inspect.py", line 2396, in _signature_from_callable
[rank0]:     raise TypeError('{!r} is not a callable object'.format(obj))
[rank0]: TypeError: None is not a callable object
```

### Steps to reproduce

CUDA_VISIBLE_DEVICES=2,3 axolotl vllm-serve examples/qwen3/rl.yaml

CUDA_VISIBLE_DEVICES=0,1 axolotl train examples/qwen3/rl.yaml --num-processes 2


### Config yaml

rl.yaml from https://github.com/axolotl-ai-cloud/axolotl-cookbook/blob/main/grpo/gsm8k.yaml
```yaml


# https://github.com/axolotl-ai-cloud/axolotl-cookbook/blob/main/grpo/gsm8k.yaml
# http://docs.axolotl.ai/docs/rlhf.html#grpo
base_model: Qwen/Qwen3-8B
# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

load_in_8bit: false
load_in_4bit: false
strict: false

torch_compile: true

rl: grpo
trl:
  beta: 0.001
  max_completion_length: 512
  use_vllm: true
  reward_funcs:
    - gsm8k_grpo.correctness_reward_func
    - gsm8k_grpo.int_reward_func
    - gsm8k_grpo.strict_format_reward_func
    - gsm8k_grpo.soft_format_reward_func
    - gsm8k_grpo.xmlcount_reward_func
  vllm_gpu_memory_utilization: 0.9
  vllm_max_model_len: 800
  num_generations: 16

chat_template: qwen3
datasets:
  - path: skrishna/gsm8k_only_answer
    type: gsm8k_grpo.axo_gsm8k_transform
dataset_prepared_path: /workspace/data/last_run_prepared
skip_prepare_dataset: true
val_set_size: 0.0
output_dir: /workspace/data/axolotl-artifacts/r1-outputs

dataloader_prefetch_factor: 32
dataloader_num_workers: 2
dataloader_pin_memory: true

gc_steps: 1

sequence_len: 800
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: false

wandb_project: gsm8k-grpo-r1
wandb_entity:
wandb_name:

gradient_accumulation_steps: 8
micro_batch_size: 16  # should match num_generations / num_gpus
num_epochs: 1

optimizer: adamw_torch_fused                                                                                                                                                                                                                              
lr_scheduler: constant_with_warmup                                                                                                                                                                                                                        
learning_rate: 1.0e-6                                                                                                                                                                                                                                     
max_grad_norm: 1.0                                                                                                                                                                                                                                        
weight_decay: 0.1                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                          
bf16: true                                                                                                                                                                                                                                                
tf32: false                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                          
gradient_checkpointing: true                                                                                                                                                                                                                              
gradient_checkpointing_kwargs:                                                                                                                                                                                                                            
  use_reentrant: false                                                                                                                                                                                                                                    
flash_attention: true                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                          
logging_steps: 1                                                                                                                                                                                                                                          
warmup_steps: 100                                                                                                                                                                                                                                         
evals_per_epoch: 1                                                                                                                                                                                                                                        
saves_per_epoch: 4 



```
I have tested on some other grpo dataset in issues, but get some other errors, no one can run normally!

### Possible solution

_No response_

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main/ec4ebfd  ·

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by salmanmohammadi** [comment]
Hi @sankexin - are you able to import the function into your python environment in a REPL/a separate script? I've found this happens if I haven't installed the module that my reward function lives in, and the training code is unable to resolve it.

**Comment by sankexin** [comment]
> Hi [@sankexin](https://github.com/sankexin) - are you able to import the function into your python environment in a REPL/a separate script? I've found this happens if I haven't installed the module that my reward function lives in, and the training code is unable to resolve it.

could you provide detailed operation steps? I'll have a try!

**Comment by salmanmohammadi** [comment]
> could you provide detailed operation steps? I'll have a try!

Looking at your issue again, did you make sure to clone the https://github.com/axolotl-ai-cloud/axolotl-cookbook repo? The config file references code which lives inside the `gsmk8_grpo.py` file in the repo. To make sure it works correctly, make sure you clone the axolotl-cookbook repo, or copy that python file into your local directory, and re run the commands *from the same directory* as your `.yaml` config file, and the `gsm8k_grpo.py` file.

**Comment by Hasnonname** [comment]
I'm seeing similar errors with KTO, using the following config, just by running `accelerate launch -m axolotl.cli.train run.yaml`. I get the following stacktrace:

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/home/has/axolotl/src/axolotl/cli/train.py", line 121, in <module>
[rank0]:     fire.Fire(do_cli)
[rank0]:   File "/home/has/.venv/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
[rank0]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank0]:   File "/home/has/.venv/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
[rank0]:     component, remaining_args = _CallAndUpdateTrace(
[rank0]:   File "/home/has/.venv/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
[rank0]:     component = fn(*varargs, **kwargs)
[rank0]:   File "/home/has/axolotl/src/axolotl/cli/train.py", line 95, in do_cli
[rank0]:     return do_train(parsed_cfg, parsed_cli_args)
[rank0]:   File "/home/has/axolotl/src/axolotl/cli/train.py", line 47, in do_train
[rank0]:     dataset_meta = load_preference_datasets(cfg=cfg, cli_args=cli_args)
[rank0]:   File "/home/has/axolotl/src/axolotl/common/datasets.py", line 133, in load_preference_datasets
[rank0]:     train_dataset, eval_dataset = load_prepare_preference_datasets(cfg)
[rank0]:   File "/home/has/axolotl/src/axolotl/utils/data/rl.py", line 201, in load_prepare_preference_datasets
[rank0]:     train_dataset = load_split(cfg.datasets, cfg)
[rank0]:   File "/home/has/axolotl/src/axolotl/utils/data/rl.py", line 153, in load_split
[rank0]:     split_datasets[i] = map_dataset(
[rank0]:   File "/home/has/axolotl/src/axolotl/utils/data/rl.py", line 63, in map_dataset
[rank0]:     sig = inspect.signature(ds_transform_fn)
[rank0]:   File "/usr/lib/python3.10/inspect.py", line 3254, in signature
[rank0]:     return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
[rank0]:   File "/usr/lib/python3.10/inspect.py", line 3002, in from_callable
[rank0]:     return _signature_from_callable(obj, sigcls=cls,
[rank0]:   File "/usr/lib/python3.10/inspect.py", line 2396, in _signature_from_callable
[rank0]:     raise TypeError('{!r} is not a callable object'.format(obj))
[rank0]: TypeError: None is not a callable object
```

This is my config file:

```yaml
# accelerate launch -m axolotl.cli.train run.yaml
base_model: trashpanda-org/Llama-3.3-70B-Aster-v0-stage3

load_in_8bit: false
load_in_4bit: false
strict: false

rl: kto
rl_beta: 0.1  # default
kto_desirable_weight: 1.0  # default
kto_undesirable_weight: 1.0  # default

remove_unused_columns: false

datasets: 
  - path: trashpanda-org/aster-kto-l3-fmt
    split: train
    type: user_defined.default
    field_prompt: "prompt"
    field_system: "system"  # optional
    field_completion: "completion"
    field_label: "label"
    prompt_format: "{prompt}"
    completion_format: "{completion}"

gradient_checkpointing: offload
gradient_checkpointing_kwargs:
  use_reentrant: true

learning_rate: 1e-6

micro_batch_size: 2
gradient_accumulation_steps: 2

num_epochs: 1
lr_scheduler: rex
warmup_ratio: 0.05

optimizer: paged_ademamix_8bit

bf16: auto
fp16:
tf32: false

plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_glu_activation: true
liger_layer_norm: true
liger_fused_linear_cross_entropy: true

deepspeed: deepspeed_configs/zero3_bf16_cpuoffload_params.json

wandb_project: Aster-v0
```
