### ISSUE TITLE
FSDP Torchao 8bit optimizer cause save checkpoint error only at the end

### ISSUE THREAD

**Issue by Nero10578** [axolotl-ai-cloud/axolotl#2744]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Expected to save checkpoint at end of run and complete normally just like it saved the checkpoint and optimizer states normally during the run.

EDIT: I realized I didn't have mid train saves. It just doesn't save the optimizer properly if quantized 4bit or 8bit optimizer are used.

### Current behaviour

```
Traceback (most recent call last):                                                                                                                                                          File "<frozen runpy>", line 198, in _run_module_as_main                                                                                                                                 
  File "<frozen runpy>", line 88, in _run_code                                                                                                                                              File "/home/arli/axolotl/src/axolotl/cli/train.py", line 121, in <module>                                                                                                               
    fire.Fire(do_cli)                                                                                                                                                                       File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 135, in Fire                                                                                  
    component_trace = _Fire(component, args, parsed_flag_args, context, name)                                                                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                             
  File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 468, in _Fire                                                                                     component, remaining_args = _CallAndUpdateTrace(                                                                                                                                      
                                ^^^^^^^^^^^^^^^^^^^^                                                                                                                                        File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace                                                                   
    component = fn(*varargs, **kwargs)                                                                                                                                                                    ^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                    
  File "/home/arli/axolotl/src/axolotl/cli/train.py", line 95, in do_cli                                                                                                                      return do_train(parsed_cfg, parsed_cli_args)                                                                                                                                          
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                            File "/home/arli/axolotl/src/axolotl/cli/train.py", line 51, in do_train                                                                                                                
    model, tokenizer, trainer = train(cfg=cfg, dataset_meta=dataset_meta)                                                                                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                 
  File "/home/arli/axolotl/src/axolotl/train.py", line 571, in train                                                                                                                          execute_training(cfg, trainer, resume_from_checkpoint)                                                                                                                                
  File "/home/arli/axolotl/src/axolotl/train.py", line 221, in execute_training                                                                                                               trainer.train(resume_from_checkpoint=resume_from_checkpoint)                                                                                                                          
  File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train                                                                         return inner_training_loop(                                                                                                                                                           
           ^^^^^^^^^^^^^^^^^^^^                                                                                                                                                             File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 2661, in _inner_training_loop                                                      
    self._maybe_log_save_evaluate(                                                                                                                                                          File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 3103, in _maybe_log_save_evaluate                                                  
    self._save_checkpoint(model, trial) 
[rank5]: Traceback (most recent call last):                                                                                                                            10:24:35 [452/1804][rank5]:   File "<frozen runpy>", line 198, in _run_module_as_main                                                                                                                        [rank5]:   File "<frozen runpy>", line 88, in _run_code                                                                                                                                   
[rank5]:   File "/home/arli/axolotl/src/axolotl/cli/train.py", line 121, in <module>                                                                                                      [rank5]:     fire.Fire(do_cli)                                                                                                                                                            
[rank5]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 135, in Fire                                                                         [rank5]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)                                                                                                    [rank5]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                    
[rank5]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 468, in _Fire                                                                        
[rank5]:     component, remaining_args = _CallAndUpdateTrace(
[rank5]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
[rank5]:     component = fn(*varargs, **kwargs)
[rank5]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/arli/axolotl/src/axolotl/cli/train.py", line 95, in do_cli
[rank5]:     return do_train(parsed_cfg, parsed_cli_args)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/arli/axolotl/src/axolotl/cli/train.py", line 51, in do_train
[rank5]:     model, tokenizer, trainer = train(cfg=cfg, dataset_meta=dataset_meta)
[rank5]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/arli/axolotl/src/axolotl/train.py", line 571, in train
[rank5]:     execute_training(cfg, trainer, resume_from_checkpoint)
[rank5]:   File "/home/arli/axolotl/src/axolotl/train.py", line 221, in execute_training
[rank5]:     trainer.train(resume_from_checkpoint=resume_from_checkpoint)
[rank5]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
[rank5]:     return inner_training_loop(
[rank5]:            ^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 2661, in _inner_training_loop
[rank5]:     self._maybe_log_save_evaluate(
[rank5]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 3103, in _maybe_log_save_evaluate
[rank5]:     self._save_checkpoint(model, trial)
[rank5]:   File "/home/arli/axolotl/src/axolotl/core/trainers/base.py", line 576, in _save_checkpoint
[rank5]:     return super()._save_checkpoint(model, trial, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 3211, in _save_checkpoint
[rank5]:     self._save_optimizer_and_scheduler(output_dir)
[rank5]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 3334, in _save_optimizer_and_scheduler
[rank5]:     save_fsdp_optimizer(
[rank5]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/utils/fsdp_utils.py", line 219, in save_fsdp_optimizer
[rank5]:     optim_state = FSDP.optim_state_dict(model, optimizer)
[rank5]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1890, in optim_state_dict
[rank5]:     return FullyShardedDataParallel._optim_state_dict_impl(
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1301, in _optim_state_dict_impl
[rank5]:     return _optim_state_dict(
[rank5]:            ^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank5]:     return func(*args, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_optim_utils.py", line 1974, in _optim_state_dict
[rank5]:     fsdp_osd_state = convert_fn(
[rank5]:                      ^^^^^^^^^^^
[rank5]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_optim_utils.py", line 1837, in _convert_state_with_flat_params
[rank5]:     unflat_state = _unflatten_optim_state(
[rank5]:                    ^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_optim_utils.py", line 165, in _unflatten_optim_state
[rank5]:     consolidated_state = _communicate_optim_state(
[rank5]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_optim_utils.py", line 243, in _communicate_optim_state
[rank5]:     tensor_buffer = value.new_zeros(*buffer_size)
[rank5]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torchao/utils.py", line 425, in _dispatch__torch_function__
[rank5]:     return func(*args, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torchao/utils.py", line 444, in _dispatch__torch_dispatch__
[rank5]:     raise NotImplementedError(
[rank5]: NotImplementedError: OptimState8bit dispatch: attempting to run unimplemented operator/function: func=<OpOverload(op='aten.new_zeros', overload='default')>, types=(<class 'torch
ao.optim.subclass_8bit.OptimState8bit'>,), arg_types=(<class 'torchao.optim.subclass_8bit.OptimState8bit'>, <class 'list'>), kwarg_types={'pin_memory': <class 'bool'>}
  File "/home/arli/axolotl/src/axolotl/core/trainers/base.py", line 576, in _save_checkpoint
    return super()._save_checkpoint(model, trial, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Steps to reproduce

Use adamw_torch_8bit optimizer and wait for the end of a train.

### Config yaml

```yaml
base_model: /home/arli/models/DeepSeek-R1-0528-Qwen3-8B

train_on_inputs: false
group_by_length: false
load_in_8bit:
load_in_4bit:
strict: false
sequence_len: 16384
bf16: auto
tf32: false
flash_attention: true

shuffle_merged_datasets: true

datasets:
  - path: /home/arli/datasets/RpR-v4/conversations-derep-deimp.jsonl
    type: input_output

dataset_prepared_path: ./lora_last_run_prepared

# Iterations
num_epochs: 1
saves_per_epoch: 1
saves_total_limit: 1

# Evaluation
val_set_size: 0.001
eval_max_new_tokens: 128
eval_sample_packing: false
evals_per_epoch: 8
eval_table_size:
# LoRA
output_dir: ./lora_out
adapter: lora
lora_model_dir:
lora_r: 128
lora_alpha: 128
lora_dropout: 0
lora_target_linear: true
peft_use_rslora: true
save_safetensors: true
#lora_mlp_kernel: true
#lora_qkv_kernel: true
#lora_o_kernel: true

save_safetensors: true

# Sampling
sample_packing: true
pad_to_sequence_len: true

# Batching
gradient_accumulation_steps: 5
micro_batch_size: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

# wandb
wandb_mode: # "offline" to save run metadata locally and not sync to the server, "disabled" to turn off wandb
wandb_project: R1-Distill-Q38B
wandb_entity: # A wandb Team name if using a Team
wandb_watch:
wandb_name: RpR-Tiny-v4
wandb_run_id: # Set the ID of your wandb run
wandb_log_model: # "checkpoint" to log model to wandb Artifacts every `save_steps` or "end" to log only at the end of training

# Optimizer
optimizer: adamw_torch_8bit
lr_scheduler: constant
learning_rate: 3e-5

# Misc
auto_resume_from_checkpoints: true
logging_steps: 1
weight_decay: 0

plugins:
  - axolotl.integrations.liger.LigerPlugin
  - axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin
cut_cross_entropy: true
liger_rope: true
liger_rms_norm: true
liger_layer_norm: true
liger_glu_activation: true
#liger_fused_linear_cross_entropy: true

unsloth_cross_entropy_loss: true
unsloth_rms_norm: true

# Multi-GPU
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_limit_all_gathers: true
  fsdp_sync_module_states: true
  fsdp_offload_params: false
  fsdp_use_orig_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: Qwen3DecoderLayer
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_forward_prefetch: true
  fsdp_activation_checkpointing: false
```

### Environment

```
PyTorch version: 2.6.0+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 24.04.2 LTS (x86_64)
GCC version: (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Clang version: Could not collect
CMake version: version 4.0.2
Libc version: glibc-2.39

Python version: 3.11.11 (main, Dec 11 2024, 16:28:39) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.11.0-26-generic-x86_64-with-glibc2.39
Is CUDA available: True
CUDA runtime version: 12.4.131
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090 Ti
GPU 1: NVIDIA GeForce RTX 3090 Ti
GPU 2: NVIDIA GeForce RTX 3090 Ti
GPU 3: NVIDIA GeForce RTX 3090
GPU 4: NVIDIA GeForce RTX 3090 Ti
GPU 5: NVIDIA GeForce RTX 3090 Ti

Nvidia driver version: 565.57.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        48 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               96
On-line CPU(s) list:                  0-95
Vendor ID:                            AuthenticAMD
Model name:                           AMD EPYC 7R13 48-Core Processor
CPU family:                           25
Model:                                1
Thread(s) per core:                   2
Core(s) per socket:                   48
Socket(s):                            1
Stepping:                             1
Frequency boost:                      enabled
CPU(s) scaling MHz:                   60%
CPU max MHz:                          2650.0000
CPU min MHz:                          1500.0000
BogoMIPS:                             5300.15
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local user_shstk clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin brs arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm debug_swap
Virtualization:                       AMD-V
L1d cache:                            1.5 MiB (48 instances)
L1i cache:                            1.5 MiB (48 instances)
L2 cache:                             24 MiB (48 instances)
L3 cache:                             192 MiB (6 instances)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-95
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Mitigation; Safe RET
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Retpolines; IBPB conditional; IBRS_FW; STIBP always-on; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] numpy==2.0.1
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] torch==2.6.0+cu124
[pip3] torchao==0.10.0
[pip3] torchaudio==2.6.0+cu124
[pip3] torchvision==0.21.0+cu124
[pip3] transformers==4.51.3
[pip3] triton==3.2.0
[conda] nccl                        2.21.5.1             ha515578_0
[conda] numpy                       2.0.1                pypi_0           pypi
[conda] nvidia-nccl-cu12            2.21.5               pypi_0           pypi
[conda] torch                       2.6.0+cu124          pypi_0           pypi
[conda] torchao                     0.10.0               pypi_0           pypi
[conda] torchaudio                  2.6.0+cu124          pypi_0           pypi
[conda] torchvision                 0.21.0+cu124         pypi_0           pypi
[conda] transformers                4.51.3               pypi_0           pypi
[conda] triton                      3.2.0                pypi_0           pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
Aphrodite Version: N/A
Aphrodite Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NODE    NODE    NODE    NODE    NODE    0-95    0               N/A
GPU1    NODE     X      NODE    NODE    NODE    NODE    0-95    0               N/A
GPU2    NODE    NODE     X      PHB     NODE    NODE    0-95    0               N/A
GPU3    NODE    NODE    PHB      X      NODE    NODE    0-95    0               N/A
GPU4    NODE    NODE    NODE    NODE     X      PHB     0-95    0               N/A
GPU5    NODE    NODE    NODE    NODE    PHB      X      0-95    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

### Possible solution

Using not the adamw_torch_8bit optimizer like adamw_torch_fused works fine but then you're losing the VRAM reduction.

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

main/6778856804e2c6d5f9903006916f9cd4bfb27756

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
We have a check that FSDPv1 + fsdp cpu offload + 8bit optimizer to fail. However, we weren't aware it also occurs without cpu offload.

Could you try FSDPv2?

```yaml
fsdp_config:
  fsdp_version: 2
  ...

# for debug for early save
save_steps: 4
```

**Comment by Nero10578** [comment]
> We have a check that FSDPv1 + fsdp cpu offload + 8bit optimizer to fail. However, we weren't aware it also occurs without cpu offload.
> 
> Could you try FSDPv2?
> 
> fsdp_config:
>   fsdp_version: 2
>   ...
> 
> # for debug for early save
> save_steps: 4

Yes I am not sure why this is the case for FSDP1. I thought I had quantized optimizer work with FSDP1 before, not sure which commit broke it or if I remembered correctly. At the moment it saves the checkpoint adapter_model.safetensor correctly but just doesn't correctly save the optimizer state so it can't continue and outputs an error at the end if I set it to only save once. But it does save the model correctly.

When I try FSDP2, it now seems to correctly save both the model and optimizer state correctly but it is not able to continue the train from a checkpoint. It spams this error:

```
apped_module.mlp.down_proj.lora_B.weight", "base_model.model.model.layers.33._checkpoint_wrapped_module.self_attn.q_proj.lora_A.weight", "base_model.model.model.layers.33._checkpoint_wrapped_module.self_attn.q_proj.lora_B.weight", "base_model.model.model.layers.33._checkpoint_wrapped_module.self_attn.k_proj.lora_A.weight", "base_model.model.model.layers.33._checkpoint_wrapped_module.self_attn.k_proj.lora_B.weight", "base_model.model.model.layers.33._checkpoint_wrapped_module.self_attn.v_proj.lora_A.weight", "base_model.model.model.layers.33._checkpoint_wrapped_module.self_attn.v_proj.lora_B.weight", "base_model.model.model.layers.33._checkpoint_wrapped_module.self_attn.o_proj.lora_A.weight", "base_model.model.model.layers.33._checkpoint_wrapped_module.self_attn.o_proj.lora_B.weight", "base_model.model.model.layers.33._checkpoint_wrapped_module.mlp.gate_proj.lora_A.weight", "base_model.model.model.layers.33._checkpoint_wrapped_module.mlp.gate_proj.lora_B.weight", "base_model.model.model.layers.33._checkpoint_wrapped_module.mlp.up_proj.lora_A.weight", "base_model.model.model.layers.33._checkpoint_wrapped_module.mlp.up_proj.lora_B.weight", "base_model.model.model.layers.33._checkpoint_wrapped_module.mlp.down_proj.lora_A.weight", "base_model.model.model.layers.33._checkpoint_wrapped_module.mlp.down_proj.lora_B.weight", "base_model.model.model.layers.34._checkpoint_wrapped_module.self_attn.q_proj.lora_A.weight", "base_model.model.model.layers.34._checkpoint_wrapped_module.self_attn.q_proj.lora_B.weight", "base_model.model.model.layers.34._checkpoint_wrapped_module.self_attn.k_proj.lora_A.weight", "base_model.model.model.layers.34._checkpoint_wrapped_module.self_attn.k_proj.lora_B.weight", "base_model.model.model.layers.34._checkpoint_wrapped_module.self_attn.v_proj.lora_A.weight", "base_model.model.model.layers.34._checkpoint_wrapped_module.self_attn.v_proj.lora_B.weight", "base_model.model.model.layers.34._checkpoint_wrapped_module.self_attn.o_proj.lora_A.weight", "base_model.model.model.layers.34._checkpoint_wrapped_module.self_attn.o_proj.lora_B.weight", "base_model.model.model.layers.34._checkpoint_wrapped_module.mlp.gate_proj.lora_A.weight", "base_model.model.model.layers.34._checkpoint_wrapped_module.mlp.gate_proj.lora_B.weight", "base_model.model.model.layers.34._checkpoint_wrapped_module.mlp.up_proj.lora_A.weight", "base_model.model.model.layers.34._checkpoint_wrapped_module.mlp.up_proj.lora_B.weight", "base_model.model.model.layers.34._checkpoint_wrapped_module.mlp.down_proj.lora_A.weight", "base_model.model.model.layers.34._checkpoint_wrapped_module.mlp.down_proj.lora_B.weight", "base_model.model.model.layers.35._checkpoint_wrapped_module.self_attn.q_proj.lora_A.weight", "base_model.model.model.layers.35._checkpoint_wrapped_module.self_attn.q_proj.lora_B.weight", "base_model.model.model.layers.35._checkpoint_wrapped_module.self_attn.k_proj.lora_A.weight", "base_model.model.model.layers.35._checkpoint_wrapped_module.self_attn.k_proj.lora_B.weight", "base_model.model.model.layers.35._checkpoint_wrapped_module.self_attn.v_proj.lora_A.weight", "base_model.model.model.layers.35._checkpoint_wrapped_module.self_attn.v_proj.lora_B.weight", "base_model.model.model.layers.35._checkpoint_wrapped_module.self_attn.o_proj.lora_A.weight", "base_model.model.model.layers.35._checkpoint_wrapped_module.self_attn.o_proj.lora_B.weight", "base_model.model.model.layers.35._checkpoint_wrapped_module.mlp.gate_proj.lora_A.weight", "base_model.model.model.layers.35._checkpoint_wrapped_module.mlp.gate_proj.lora_B.weight", "base_model.model.model.layers.35._checkpoint_wrapped_module.mlp.up_proj.lora_A.weight", "base_model.model.model.layers.35._checkpoint_wrapped_module.mlp.up_proj.lora_B.weight", "base_model.model.model.layers.35._checkpoint_wrapped_module.mlp.down_proj.lora_A.weight", "base_model.model.model.layers.35._checkpoint_wrapped_module.mlp.down_proj.lora_B.weight".                    [rank0]:[W604 22:33:42.734848537 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
```

This is the config:

```
base_model: /home/arli/models/DeepSeek-R1-0528-Qwen3-8B

train_on_inputs: false
group_by_length: false
load_in_8bit:
load_in_4bit:
strict: false
sequence_len: 16384
bf16: auto
tf32: false
flash_attention: true

shuffle_merged_datasets: true

datasets:
  - path: /home/arli/datasets/RpR-v4/conversations-R1-derep-deimp.jsonl
    type: input_output

dataset_prepared_path: ./lora_last_run_prepared

# Iterations
num_epochs: 1
saves_per_epoch: 8
saves_total_limit: 8

# Evaluation
val_set_size: 0.001
eval_max_new_tokens: 128
eval_sample_packing: false
evals_per_epoch: 8
eval_table_size:
# LoRA
output_dir: ./lora_out_test
adapter: lora
lora_model_dir:
lora_r: 128
lora_alpha: 128
lora_dropout: 0
lora_target_linear: true
peft_use_rslora: true
#lora_mlp_kernel: true
#lora_qkv_kernel: true
#lora_o_kernel: true

#save_safetensors: true

# Sampling
sample_packing: true
pad_to_sequence_len: true

# Batching
gradient_accumulation_steps: 4
micro_batch_size: 1
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: false

# wandb
wandb_mode: # "offline" to save run metadata locally and not sync to the server, "disabled" to turn off wandb
wandb_project: R1-Distill-Q38B
wandb_entity: # A wandb Team name if using a Team
wandb_watch:
wandb_name: RpR-Tiny-v4
wandb_run_id: # Set the ID of your wandb run
wandb_log_model: # "checkpoint" to log model to wandb Artifacts every `save_steps` or "end" to log only at the end of training

# Optimizer
optimizer: adamw_torch_8bit
lr_scheduler: constant
learning_rate: 1e-5

# Misc
auto_resume_from_checkpoints: true
logging_steps: 1
weight_decay: 0

plugins:
  - axolotl.integrations.liger.LigerPlugin
  - axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin
cut_cross_entropy: true
liger_rope: true
liger_rms_norm: true
liger_layer_norm: true
liger_glu_activation: true
#liger_fused_linear_cross_entropy: true

unsloth_cross_entropy_loss: true
unsloth_rms_norm: true

fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_limit_all_gathers: true
  fsdp_offload_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: Qwen3DecoderLayer
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_activation_checkpointing: true
  fsdp_reshard_after_forward: true
  fsdp_version: 2
```

I also have a question regarding FSDP2 though, since the command below exists to merge the FSDP checkpoint back to safetensors, why not make axolotl automatically be able to safe as safetensors with FSDP2 enabled?

```
python -m axolotl.cli.merge_sharded_fsdp_weights \
    /path/to/your/original_training_config.yml \
    --checkpoint_dir outputs/checkpoint_dir \
    --output_path outputs/merged_dir \
    --safe_serialization True
```
