### ISSUE TITLE
Transformers 4.52.x breaks liger and prevents train from starting

### ISSUE THREAD

**Issue by Nero10578** [axolotl-ai-cloud/axolotl#2767]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Liger kernels should work as expected as in previous transformers 4.51.3 version and older. It see

### Current behaviour

I was diagnosing the other issue of FSDP offloading being broken and the quantized optimizer errors, so I did a clean env and latest axolotl commit install. I ended up encountering a new bug instead.

```
from transformers.models.gemma2.modeling_gemma2 import (
[rank6]: ImportError: cannot import name '_CONFIG_FOR_DOC' from 'transformers.models.gemma2.modeling_gemma2'
```

I believe it is related to this? https://github.com/huggingface/trl/issues/3480

I am using the latest liger version after the merge of the fix mentioned there and also tried installing from source but this error persists.

I tried using the older transformers 4.51.3 version that works before but now I get this error instead.

```
[rank2]: AttributeError: 'NoneType' object has no attribute 'column_names' 
```

### Steps to reproduce

In the latest commit with the requirements now installing transformers 4.52.xx versions, it causes liger to stop working and I can't start the train with liger enabled.

### Config yaml

```yaml
base_model: /home/arli/models/DeepSeek-R1-Distill-Llama-70B

train_on_inputs: false
group_by_length: false
load_in_8bit:
load_in_4bit: true
strict: false
sequence_len: 4096
bf16: auto
tf32: false
flash_attention: true

shuffle_merged_datasets: true

datasets:
  - path: /home/arli/datasets/RpR-v4/conversations-derep-deimp.jsonl
    type: input_output

dataset_prepared_path: ./last_run_prepared

# Iterations
num_epochs: 1
saves_per_epoch: 1
saves_total_limit: 1

# Evaluation
val_set_size: 0.0025
eval_max_new_tokens: 128
eval_sample_packing: false
evals_per_epoch: 8
eval_table_size:

# LoRA
output_dir: ./qlora_out_RpR_test
adapter: qlora
lora_model_dir:
lora_r: 64
lora_alpha: 64
lora_dropout: 0
lora_target_linear: true
peft_use_rslora: true
save_safetensors: true
#loraplus_lr_ratio: 8

# Sampling
sample_packing: true
pad_to_sequence_len: true

# Batching
gradient_accumulation_steps: 4
micro_batch_size: 1
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: false

# wandb
wandb_mode: # "offline" to save run metadata locally and not sync to the server, "disabled" to turn off wandb
wandb_project: R1-70B-RpR
wandb_entity: # A wandb Team name if using a Team
wandb_watch:
wandb_name: R1-70B-RpR-v4-Large
wandb_run_id: # Set the ID of your wandb run
wandb_log_model: # "checkpoint" to log model to wandb Artifacts every `save_steps` or "end" to log only at the end of training

# Optimizer
optimizer: adamw_torch_4bit
lr_scheduler: constant
learning_rate: 1e-5
#warmup_ratio: 0.1

# Misc
auto_resume_from_checkpoints: true
logging_steps: 1
weight_decay: 0

plugins:
  - axolotl.integrations.liger.LigerPlugin
  - axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin
cut_cross_entropy: true
liger_rope: true
liger_rms_norm: true
liger_layer_norm: true
liger_glu_activation: true
#liger_fused_linear_cross_entropy: true

#unsloth_cross_entropy_loss: true
#unsloth_rms_norm: true

# Multi-GPU
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_limit_all_gathers: true
  fsdp_sync_module_states: true
  fsdp_offload_params: false
  fsdp_use_orig_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_forward_prefetch: false
  fsdp_activation_checkpointing: true
```

### Possible solution

Seems using commit 787880215b3ab32ccaf81c1b2e9588c6f3e6e764 which uses transformers 4.51.3 makes it work again. But now I still get the broken FSDP offload issue and the error during saving caused by quantized optimizers.

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.12

### axolotl branch-commit

main/7909bfb076a67c31d407f89212e6143afa4aa05d

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.
