### ISSUE TITLE
axolotl 0.10.0 is pinned on torch 2.6.0

### ISSUE THREAD

**Issue by hongbo-miao** [axolotl-ai-cloud/axolotl#2812]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I am hoping using `uv sync` way to install axolotl and PyTorch 2.7.1 to able to use RTX 5090.

### Current behaviour

axolotl 0.10.0 is pinned on torch 2.6.0, and cannot use `uv sync` way to use torch 2.7.1

### Steps to reproduce

pyproject.toml

```toml
[project]
name = "hm-axolotl"
version = "1.0.0"
requires-python = "~=3.11.0"
dependencies = [
  "axolotl==0.10.0",
  "torch==2.7.1",
]

[tool.uv]
package = false
required-version = ">=0.6.0"

[tool.uv.sources]
torch = [{ index = "pytorch-cu128" }]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
```

`uv sync` will return error

```sh
  × No solution found when resolving dependencies for split (python_full_version >= '3.11.0' and python_full_version < '3.12' and sys_platform == 'linux'):
  ╰─▶ Because axolotl==0.10.0 depends on torch==2.6.0 and your project depends on axolotl==0.10.0, we can conclude that your project depends on torch==2.6.0.
      And because your project depends on torch==2.7.1, we can conclude that your project's requirements are unsatisfiable.
error: Recipe `uv-install-dependencies` failed on line 5 with exit code 1
```

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hey, did you try to install torch first before installing axolotl?

We do a check where:
```
            # detect the version of torch already installed
            # and set it so dependencies don't clobber the torch version
            try:
                torch_version = version("torch")
            except PackageNotFoundError:
                torch_version = "2.6.0"  # default to torch 2.6
```

For pip, there's a no build isolation flag, is there one for uv?

**Comment by hongbo-miao** [comment]
Thanks @NanoCode012 ! I got some suggestions from uv repo [here](https://github.com/astral-sh/uv/issues/14178).

As a workaround way, I found to be able to run

```sh
uv run axolotl fetch examples
uv run axolotl preprocess examples/qwen3/8b-qat-fsdp2.yml
uv run axolotl train examples/qwen3/8b-qat-fsdp2.yml
```

I need do

```toml
[project]
name = "hm-axolotl"
version = "1.0.0"
requires-python = "~=3.11.0"
dependencies = [
  "axolotl==0.10.0",
  "deepspeed==0.17.1",
  "flash-attn==2.8.0.post2",
  "torch==2.7.1",
]

[tool.uv]
package = false
required-version = ">=0.6.0"
no-build-isolation-package = ["flash-attn"]

[[tool.uv.dependency-metadata]]
name = "axolotl"
version = "0.10.0"
requires-dist = [
  "torch==2.7.1",
  "colorama==0.4.6",
  "click==8.2.1",
  "python-dotenv==1.1.0",
  "requests==2.32.4",
  "pydantic==2.11.7",
  "transformers==4.52.4",
  "bitsandbytes==0.46.0",
  "peft==0.15.2",
  "addict==2.4.0",
  "fastcore==1.8.4",
  "datasets==3.6.0",
  "pillow==11.2.1",
  "fire==0.7.0",
  "numba==0.61.2",
  "axolotl-contribs-lgpl==0.0.6",
  "hf-transfer==0.1.9",
]

[tool.uv.sources]
torch = [{ index = "pytorch-cu128" }]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
```

Note

1. `"axolotl[flash-attn,deepspeed]==0.10.0"` does not help install `flash-attn` and `deepspeed` when provide `[[tool.uv.dependency-metadata]]` for `axolotl`. So I provide `"deepspeed==0.17.1"` and `"flash-attn==2.8.0.post2"` under `dependencies`.
2. When I provide `"torch==2.7.1"` under `dependencies`, it will install newer versions:
```
 - nvidia-cublas-cu12==12.6.4.1
 + nvidia-cublas-cu12==12.8.3.14
 - nvidia-cuda-cupti-cu12==12.6.80
 + nvidia-cuda-cupti-cu12==12.8.57
 - nvidia-cuda-nvrtc-cu12==12.6.77
 + nvidia-cuda-nvrtc-cu12==12.8.61
 - nvidia-cuda-runtime-cu12==12.6.77
 + nvidia-cuda-runtime-cu12==12.8.57
 - nvidia-cudnn-cu12==9.5.1.17
 + nvidia-cudnn-cu12==9.7.1.26
 - nvidia-cufft-cu12==11.3.0.4
 + nvidia-cufft-cu12==11.3.3.41
 - nvidia-cufile-cu12==1.11.1.6
 + nvidia-cufile-cu12==1.13.0.11
 - nvidia-curand-cu12==10.3.7.77
 + nvidia-curand-cu12==10.3.9.55
 - nvidia-cusolver-cu12==11.7.1.2
 + nvidia-cusolver-cu12==11.7.2.55
 - nvidia-cusparse-cu12==12.5.4.2
 + nvidia-cusparse-cu12==12.5.7.53
 - nvidia-nvjitlink-cu12==12.6.85
 + nvidia-nvjitlink-cu12==12.8.61
 - nvidia-nvtx-cu12==12.6.77
 + nvidia-nvtx-cu12==12.8.55
```

However, I still met

> CUDA error: an illegal memory access was encountered

but I think this is out of scope of this issue.

I am wondering if axolotl could provide something like unsloth https://github.com/unslothai/unsloth/blob/db8185dd114b799256e5429fbc1708418b54e944/pyproject.toml#L342-L346

```toml
[project.optional-dependencies]
cu128-torch270 = [
    "unsloth[huggingface]",
    "bitsandbytes>=0.45.5",
    "unsloth[cu128onlytorch270]",
]
```

so I can install by `unsloth[cu128-torch270]` for certain torch version and corresponding other dependency versions.

Thank you! ☺️

**Comment by hongbo-miao** [comment]
Got more suggestion on uv side at https://github.com/astral-sh/uv/issues/14178#issuecomment-2993511159

Here is my current version which is more cleaner:

```toml
[project]
name = "hm-axolotl"
version = "1.0.0"
requires-python = "~=3.11.0"
dependencies = [
  "axolotl[deepspeed]==0.10.0",
  "flash-attn==2.8.0.post2",
]

[tool.uv]
package = false
required-version = ">=0.6.0"
no-build-isolation-package = ["flash-attn"]
override-dependencies = ["torch==2.7.1"]

[tool.uv.sources]
torch = [{ index = "pytorch-cu128" }]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
```

I think I can close for now. Thanks!
