### ISSUE TITLE
[Bug] Tokenized dataset hash does not factor in `data_files`

### ISSUE THREAD

**Issue by NanoCode012** [axolotl-ai-cloud/axolotl#341]
If we use local dataset and only change the `data_files` parameter, it would reuse the old tokenized dataset still since it was not factored into the hash.

```yaml
datasets:
  - path: json
    type: sharegpt:chat
    data_files: data.jsonl
```

https://github.com/OpenAccess-AI-Collective/axolotl/blob/fe285430bc26f34cccfdf7aec3b437a7eea0b85c/src/axolotl/utils/data.py#L52

https://github.com/OpenAccess-AI-Collective/axolotl/blob/fe285430bc26f34cccfdf7aec3b437a7eea0b85c/src/axolotl/utils/data.py#L317
