### ISSUE TITLE
Dolly prompt format

### ISSUE THREAD

**Issue by thistleknot** [axolotl-ai-cloud/axolotl#720]
### What piece of documentation is affected?

datasets

### What part(s) of the article would you like to see updated?

I'd like to see how to use this dataset format which is 
question : context -> answer
i.e. the expectation is giving the model a question, the model will generate a context then answer

which isn't self explanatory until you see the url I posted

but I don't see that in the datasets format

I believe this is a closed book qa response, but I also see this style used by chatgpt.  Kind of like a chain of thought response.  When given a question, generates background context then an extractive (or abstractive) answer from the context.

### Additional Information

https://huggingface.co/datasets/lionelchg/dolly_closed_qa/viewer/default/train?row=0

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by thistleknot** [comment]
note text
![image](https://github.com/OpenAccess-AI-Collective/axolotl/assets/5154106/22df9fe5-1d98-4251-b1bc-97b1181f1ccb)

**Comment by NanoCode012** [comment]
Please try the below.
```yml
  - path: repo
    type:
      system_prompt: ""
      system_format: ""
      field_system:
      field_instruction: instruction
      field_input: context
      field_output: response

      format: |-
        ### Instruction: {instruction}
        ### Context: {input}
        ### Answer: 
      no_input_format: |-
        ### Instruction: {instruction}
        ### Answer: 
```
