### ISSUE TITLE
`RuntimeError: CUDA error: unknown error.` Happens between `Saving the dataset` and `Loading prepared dataset from disk`

### ISSUE THREAD

**Issue by neoneye** [axolotl-ai-cloud/axolotl#840]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Fine tuning of llama2 using axolotl. I have done it 6 times successfully, and some times with hickups.

### Current behaviour

Stacktrace shows: `RuntimeError: CUDA error: unknown error`
![Screenshot 2023-11-09 at 11 33 19](https://github.com/OpenAccess-AI-Collective/axolotl/assets/147971/1ff20a14-725b-437f-86ba-c03a1a0996b2)

After the error axolotl continues, but ends up hanging. The python3 process used around 60% cpu without updating the screen. After 15 minutes of hanging, I killed it. I suspect the hanging has to do with the error.
![Screenshot 2023-11-09 at 12 13 52](https://github.com/OpenAccess-AI-Collective/axolotl/assets/147971/82a3c549-b750-4ab4-971d-3742e9e9a302)
The last message printed is `packing_efficiency_estimate: 1.0 total_num_tokens per device: 318948`

The server:
![Screenshot 2023-11-09 at 12 22 06](https://github.com/OpenAccess-AI-Collective/axolotl/assets/147971/6caecea1-0d66-40c0-bf6d-a789c2e94a9c)

### Steps to reproduce

I used this docker image: [winglian/axolotl:main-py3.10-cu118-2.0.1](https://hub.docker.com/layers/winglian/axolotl/main-py3.10-cu118-2.0.1/images/sha256-0da75e481402756cca380756b4493150229320776f20c2e67c751fca69690ada?context=explore)

Last pushed: Nov 9, 2023 at 2:56 am

Digest:sha256:4edc67dbc7f7acdfd37ad4b1dce29eb3441ab54faca59791048e75bb6b772bce

### Config yaml

```yaml
# This file is based on this file: https://github.com/OpenAccess-AI-Collective/axolotl/blob/main/examples/llama-2/qlora.yml
base_model: NousResearch/Llama-2-7b-hf
base_model_config: NousResearch/Llama-2-7b-hf
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: neoneye/gameoflife-v1
    type: completion
dataset_prepared_path: last_run_prepared
val_set_size: 0.05
output_dir: ./qlora-out

adapter: qlora
lora_model_dir:

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: "llama-2-7b-simonsolver-v7"
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model: "checkpoint"

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 4
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 0.05
eval_table_size:
save_steps:
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

# Upload to HuggingFace
hub_model_id: neoneye/llama-2-7b-simonsolver-v7
```

### Possible solution

Since yesterday there has been this commit: [f544ab2bed5](https://github.com/OpenAccess-AI-Collective/axolotl/commit/f544ab2bed513bef269e6887d35c8aa12a852473). There are several changes to the dockerfile.

Yesterday I got another error, and is reported here: #835

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main/f544ab2

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
